# Importing Libraries

In [287]:
# Importing Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [288]:
# Set the maximum number of columns to display to None, which means showing all columns
pd.set_option('display.max_columns', None)

# Set the maximum number of rows to display to 200
pd.set_option('display.max_rows', 200)

# Load the data

In [289]:
file_path = 'D:/UCO_CourseWork/Programing for analytics/ProjectProposal/25kperm.xlsx'
df = pd.read_excel(file_path)
df.head()

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,REFILE,ORIG_FILE_DATE,PREVIOUS_SWA_CASE_NUMBER_STATE,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,EMPLOYER_ADDRESS_2,EMPLOYER_CITY,EMPLOYER_STATE_PROVINCE,EMPLOYER_COUNTRY,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,EMPLOYER_PHONE_EXT,EMPLOYER_NUM_EMPLOYEES,EMPLOYER_YEAR_COMMENCED_BUSINESS,NAICS_CODE,FW_OWNERSHIP_INTEREST,EMP_CONTACT_NAME,EMP_CONTACT_ADDRESS_1,EMP_CONTACT_ADDRESS_2,EMP_CONTACT_CITY,EMP_CONTACT_STATE_PROVINCE,EMP_CONTACT_COUNTRY,EMP_CONTACT_POSTAL_CODE,EMP_CONTACT_PHONE,EMP_CONTACT_EMAIL,AGENT_ATTORNEY_NAME,AGENT_ATTORNEY_FIRM_NAME,AGENT_ATTORNEY_PHONE,AGENT_ATTORNEY_PHONE_EXT,AGENT_ATTORNEY_ADDRESS_1,AGENT_ATTORNEY_ADDRESS_2,AGENT_ATTORNEY_CITY,AGENT_ATTORNEY_STATE_PROVINCE,AGENT_ATTORNEY_COUNTRY,AGENT_ATTORNEY_POSTAL_CODE,AGENT_ATTORNEY_EMAIL,PW_TRACK_NUMBER,PW_SOC_CODE,PW_SOC_TITLE,PW_SKILL_LEVEL,PW_WAGE,PW_UNIT_OF_PAY,PW_WAGE_SOURCE,PW_SOURCE_NAME_OTHER,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_TO,WAGE_OFFER_UNIT_OF_PAY,WORKSITE_ADDRESS_1,WORKSITE_ADDRESS_2,WORKSITE_CITY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,JOB_TITLE,MINIMUM_EDUCATION,JOB_EDUCATION_MIN_OTHER,MAJOR_FIELD_OF_STUDY,REQUIRED_TRAINING,REQUIRED_TRAINING_MONTHS,REQUIRED_FIELD_OF_TRAINING,REQUIRED_EXPERIENCE,REQUIRED_EXPERIENCE_MONTHS,ACCEPT_ALT_FIELD_OF_STUDY,ACCEPT_ALT_MAJOR_FLD_OF_STUDY,ACCEPT_ALT_COMBO,ACCEPT_ALT_COMBO_EDUCATION,ACCEPT_ALT_COMBO_ED_OTHER,ACCEPT_ALT_COMBO_EDUCATION_YRS,ACCEPT_FOREIGN_EDUCATION,ACCEPT_ALT_OCCUPATION,ACCEPT_ALT_OCCUPATION_MONTHS,ACCEPT_ALT_JOB_TITLE,JOB_OPP_REQUIREMENTS_NORMAL,FOREIGN_LANGUAGE_REQUIRED,SPECIFIC_SKILLS,COMBINATION_OCCUPATION,OFFERED_TO_APPL_FOREIGN_WORKER,FOREIGN_WORKER_LIVE_ON_PREM,FOREIGN_WORKER_LIVE_IN_DOM_SER,FOREIGN_WORKER_LIVE_IN_DOM_SVC_CNT,PROFESSIONAL_OCCUPATION,APP_FOR_COLLEGE_U_TEACHER,COMPETITIVE_PROCESS,BASIC_RECRUITMENT_PROCESS,TEACHER_SELECT_DATE,TEACHER_PUB_JOURNAL_NAME,ADD_RECRUIT_INFORMATION,SWA_JOB_ORDER_START_DATE,SWA_JOB_ORDER_END_DATE,SUNDAY_EDITION_NEWSPAPER,FIRST_NEWSPAPER_NAME,FIRST_ADVERTISEMENT_START_DATE,SECOND_NEWSPAPER_AD_NAME,SECOND_ADVERTISEMENT_TYPE,SECOND_AD_START_DATE,JOB_FAIR_FROM_DATE,JOB_FAIR_TO_DATE,ON_CAMPUS_RECRUITING_FROM_DATE,ON_CAMPUS_RECRUITING_TO_DATE,EMPLOYER_WEBSITE_FROM_DATE,EMPLOYER_WEBSITE_TO_DATE,PRO_ORG_AD_FROM_DATE,PRO_ORG_ADVERTISEMENT_TO_DATE,JOB_SEARCH_WEBSITE_FROM_DATE,JOB_SEARCH_WEBSITE_TO_DATE,PVT_EMPLOYMENT_FIRM_FROM_DATE,PVT_EMPLOYMENT_FIRM_TO_DATE,EMPLOYEE_REF_PROG_FROM_DATE,EMPLOYEE_REFERRAL_PROG_TO_DATE,CAMPUS_PLACEMENT_FROM_DATE,CAMPUS_PLACEMENT_TO_DATE,LOCAL_ETHNIC_PAPER_FROM_DATE,LOCAL_ETHNIC_PAPER_TO_DATE,RADIO_TV_AD_FROM_DATE,RADIO_TV_AD_TO_DATE,EMP_RECEIVED_PAYMENT,PAYMENT_DETAILS,BARGAINING_REP_NOTIFIED,POSTED_NOTICE_AT_WORKSITE,LAYOFF_IN_PAST_SIX_MONTHS,US_WORKERS_CONSIDERED,COUNTRY_OF_CITIZENSHIP,FOREIGN_WORKER_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_EDUCATION,FOREIGN_WORKER_EDUCATION_OTHER,FOREIGN_WORKER_INFO_MAJOR,FOREIGN_WORKER_YRS_ED_COMP,FOREIGN_WORKER_INST_OF_ED,FOREIGN_WORKER_ED_INST_ADD_1,FOREIGN_WORKER_ED_INST_ADD_2,FOREIGN_WORKER_ED_INST_CITY,FOREIGN_WORKER_ED_INST_STATE_P,FOREIGN_WORKER_ED_INST_COUNTRY,FOREIGN_WORKER_ED_INST_POST_CD,FOREIGN_WORKER_TRAINING_COMP,FOREIGN_WORKER_REQ_EXPERIENCE,FOREIGN_WORKER_ALT_ED_EXP,FOREIGN_WORKER_ALT_OCC_EXP,FOREIGN_WORKER_EXP_WITH_EMPL,FOREIGN_WORKER_EMPL_PAY_FOR_ED,FOREIGN_WORKER_CURR_EMPLOYED,EMPLOYER_COMPLETED_APPLICATION,PREPARER_NAME,PREPARER_TITLE,PREPARER_EMAIL,EMP_INFO_DECL_NAME,EMP_DECL_TITLE
0,A-22262-24149,Withdrawn,2022-10-02,2022-10-02,N,NaT,NaN,N,Westgate Shellworld Inc,7012 Muncipal Drive,NaN,Orlando,FLORIDA,UNITED STATES OF AMERICA,32819,4074475040,NaN,45,1988.0,453220,N,Samia Ahmed,7012 Municipal Drive,NaN,Orlando,FLORIDA,UNITED STATES OF AMERICA,32819,4074475040 122,sahmed@oceanairenterprises.com,FRANCES DELAFUENTE,DELAFUENTE LAW LLC,7862929030,NaN,3105 NW 107 AVENUE,SUITE 400 G-2,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33172,MICHELLE@DLGPA.COM,P10021356781640,41-2031.00,RETAIL SALESPERSONS,Level I,20758.0,Year,OES,NaN,2022-06-21,2022-09-20,22880.0,NaN,Year,5870 US HWY 192,NaN,KISSIMMEE,FLORIDA,34746,SALES CLERK,NaN,NaN,NaN,N,NaN,NaN,N,NaN,N,NaN,N,NaN,NaN,NaN,N,N,NaN,NaN,Y,N,NONE,N,Y,N,N,NaN,N,N,NaN,NaN,NaT,NaN,NaN,2022-07-20,2022-08-24,Y,ORLANDO SENTINEL,2022-07-24,ORLANDO SENTINEL,Newspaper,2022-07-31,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,N,NaN,NaN,Y,N,NaN,NICARAGUA,NICARAGUA,NaN,High School,NaN,HIGH SCHOOL DIPLOMA,2010.0,INSTITUTO PUBLICO DE YALAGUINA,"DEL POLIDEPORTIVO MUNICIPAL, 400 MTRS. AL SURO...",NaN,SOMOTO,MADRIZ,NICARAGUA,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,FRANCES DELAFUENTE,ATTORNEY,MICHELLE@DLGPA.COM,SAMIA AHMED,OWNER
1,A-21187-12839,Certified-Expired,2022-02-03,2022-10-03,N,NaT,NaN,N,"NIKE, INC.",ONE BOWERMAN DRIVE,NaN,BEAVERTON,OREGON,UNITED STATES OF AMERICA,97005,503-671-6453,NaN,35000,1969.0,316210,N,Diana L Loveless,One Bowerman Drive,NaN,Beaverton,OREGON,UNITED STATES OF AMERICA,97005,503-532-3394,Diana.Loveless@nike.com,Chad T Li,Berry Appleman Leiden LLP,4697931827,NaN,"2400 N Glenville Drive, Building A",Suite 100,Richardson,TEXAS,UNITED STATES OF AMERICA,75082,chad.li@BAL.com,P10021127296744,11-2021,Marketing Managers,Level IV,167378.0,Year,OES,NaN,2021-10-21,2022-06-30,167378.0,NaN,Year,One Bowerman Dr.,NaN,Beaverton,OREGON,97005,Digital Services and Experiences Manager- Asia...,Master's,NaN,See H.14,N,NaN,NaN,Y,36.0,N,NaN,N,NaN,NaN,NaN,Y,Y,36.0,See H.14,N,N,Employer will accept Masters degree in Busines...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-11-22,2021-12-23,Y,The Oregonian,2021-12-05,The Oregonian,Newspaper,2021-12-12,NaT,NaT,NaT,NaT,2021-11-16,2021-12-23,NaT,NaT,2021-12-06,2021-12-13,NaT,NaT,NaT,NaT,NaT,NaT,2021-12-07,2021-12-10,NaT,NaT,N,NaN,NaN,Y,N,NaN,THAILAND,THAILAND,L-1,Master's,NaN,BUSINESS ADMINISTRATION,2008.0,SIAM UNIVERSITY,"38 PETCHKASEM RD, BANG WA, KHET PHASI CHAROEN",KRUNG THEP MAHA NAKHON,BANGKOK,NaN,THAILAND,10160,NaN,N,NaN,Y,N,N,Y,N,Chad T Li,Associate Attorney,chad.li@BAL.com,Diana Loveless,Immigration Program Consultant
2,A-21327-77110,Denied,2021-11-30,2022-10-03,N,NaT,NaN,N,RIVERY TECHNOLOGIES INC,500 7TH AVENUE,6TH FLOOR,NEW YORK,NEW YORK,UNITED STATES OF AMERICA,10018,212-671-0853,NaN,26,2019.0,54199,N,Michal Tshukati,500 7th Avenue,6th Floor,New York,NEW YORK,UNITED STATES OF AMERICA,10018,212-671-0853,suppliers@rivery.io,Rakhel S Milstein,Milstein Law Group PLLC,2129811981,NaN,"61 Broadway, Suite 2824",NaN,New York,NEW YORK,UNITED STATES OF AMERICA,10006,rsm@milsteinlg.com,P10021025032043,11-2021,Chief Executive Officer,Level IV,224307.0,Year,OES,NaN,2021-06-07,2021-09-05,224307.0,NaN,Year,500 7th Avenue,6th Floor,New York,NEW YORK,10018,Chief Executive Officer,Bachelor's,NaN,"Information Systems, Computer Engineering, or ...",N,NaN,NaN,N,NaN,N,NaN,N,NaN,NaN,NaN,Y,Y,120.0,Chief Executive Officer of a business intellig...,Y,N,Must have a Bachelors Degree in Information Sy...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-07-30,2021-09-02,Y,The New York Post,2021-08-15,The New York Post,Newspaper,2021-08-22,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2021-08-18,2021-09-16,NaT,NaT,NaT,NaT,NaT,NaT,2021-08-18,2021-08-18,2021-08-21,2021-08-21,N,NaN,NaN,Y,N,NaN,ISRAEL,ISRAEL,E-2,Bachelor's,NaN,INFORMATION SYSTEMS ENGINEERING,2002.0,BEN GURION UNIVERSITY OF THE NEGEV,1 BEN GURION AVENUE,NaN,BEER SHEVA,NEGEV,ISRAEL,8499000,NaN,NaN,NaN,Y,N,N,Y,N,Rakhel S Milstein,Attorney,rsm@milsteinlg.com,Aviv Noy,CoFounder
3,A-21342-83195,Certified-Expired,2022-02-03,2022-10-03,N,NaT,NaN,N,ESRI INC.,380 NEW YORK ST.,NaN,REDLANDS,CALIFORNIA,UNITED STATES OF AMERICA,92373,9097932853,NaN,4000,1969.0,511210,N,Vinesh Patel,380 New York St.,NaN,Redlands,CALIFORNIA,UNITED STATES OF AMERICA,92373,9097932853,vinesh_patel@esri.com,Jessica L Cross,"Ogletree, Deakins, Nash, Smoak Stewart, PC",2022630162,NaN,"1909 K Street, N.W.",Suite 1000,Washington,DISTRICT OF COLUMBIA,UNITED STATES OF AMERICA,20006,jessica.cross@ogletree.com,P10021137319941,11-2021,Marketing Managers,Level III,135990.0,Year,OES,NaN,2021-10-28,2022-06-30,135990.0,NaN,Year,55 Miracle Mile,Suite 250,Coral Gables,FLORIDA,33134,Business Development Manager,Master's,NaN,Business Administration,N,NaN,NaN,Y,36.0,Y,"Engineering any field, GIS, or related field o...",N,NaN,NaN,NaN,Y,Y,36.0,job offered or related occupation,Y,N,Applicants must have demonstrated experience w...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-10-28,2021-11-30,Y,Miami Herald,2021-12-19,Miami Herald,Newspaper,2021-12-26,NaT,NaT,NaT,NaT,2021-10-29,2021-11-12,NaT,NaT,2021-12-19,2022-01-02,NaT,NaT,NaT,NaT,NaT,NaT,2021-12-23,2021-12-29,NaT,NaT,N,NaN,NaN,Y,N,NaN,CANADA,COLOMBIA,H-1B,Master's,NaN,CIVIL ENGINEERING,2014.0,RYERSON UNIVERSITY,350 VICTORIA ST,NaN,TORONTO,ONTARIO,CANADA,M5B 2K3,NaN,N,NaN,Y,N,N,Y,N,Jessica L Cross,Attorney,jessica.cross@ogletree.com,Vinesh Patel,Global Mobility Coordinator
4,A-21349-86725,Certified-Expired,2022-02-03,2022-10-03,N,NaT,NaN,N,INGURAN LLC DBA STGENETICS,22575 STATE HWY 6 SOUTH,NaN,NAVASOTA,TEXAS,UNITED STATES OF AMERICA,77868,936-870-3960,199,666,2002.0,115210,N,Hayley R Harris,22575 State Hwy 6 South,NaN,Navasota,TEXAS,UNITED STATES OF AMERICA,77808,936-870-3960 198,hayley.harris@stgen.com,Beatriz Trillos Ballerini,"Trillos Ballerini Law Firm, P.C.",7137397272,NaN,3000 Weslayan Street,Suite 210,Houston,TEXAS,UNITED STATES OF AMERICA,77027,perm@tbvisas.com,P10021040066303,11-2021,Marketing Managers,Level IV,179754.0,Year,OES,NaN,2021-06-30,2021-09-28,179754.0,NaN,Year,22575 State Highway 6 South,NaN,Navasota,TEXAS,77868,"Business Development Manager Asia, Oceania, Mi...",Master's,NaN,Business Administration,N,NaN,NaN,Y,60.0,Y,Marketing or Veterinary Medicine,N,NaN,NaN,NaN,Y,N,NaN,NaN,Y,N,60 MONTHS OF EMPLOYMENT EXPERIENCE AS A MARKET...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-08-24,2021-09-24,Y,The Eagle,2021-09-05,The Eagle,Newspaper,2021-09-12,NaT,NaT,NaT,NaT,NaT,NaT,2021-09-02,2021-10-01,2021-08-31,2021-09-30,NaT,NaT,NaT,NaT,NaT,NaT,2021-09-09,2021-09-15,NaT,NaT,N,NaN,NaN,Y,N,NaN,UNITED KINGDOM,INDIA,Not in USA,Master's,NaN,BUSINESS ADMINISTRATION,2005.0,UNIVERSITY OF BIRMINGHAM,EDGBASTON,NaN,BIRMINGHAM,NaN,UNITED KINGDOM,B15 2TT,NaN,Y,NaN,NaN,N,N,Y,N,Beatriz Trillos Ballerini,Attorney,perm@tbvisas.com,Steven Sfamenos,Human Resources Director

# Initial Data Inspection

##  Data Information

In [290]:
# Display basic information about the dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Columns: 154 entries, CASE_NUMBER to EMP_DECL_TITLE
dtypes: datetime64[ns](30), float64(10), int64(1), object(113)
memory usage: 29.4+ MB
None

In [291]:
# Show the first few rows of the dataset
df.head()

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,REFILE,ORIG_FILE_DATE,PREVIOUS_SWA_CASE_NUMBER_STATE,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,EMPLOYER_ADDRESS_2,EMPLOYER_CITY,EMPLOYER_STATE_PROVINCE,EMPLOYER_COUNTRY,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,EMPLOYER_PHONE_EXT,EMPLOYER_NUM_EMPLOYEES,EMPLOYER_YEAR_COMMENCED_BUSINESS,NAICS_CODE,FW_OWNERSHIP_INTEREST,EMP_CONTACT_NAME,EMP_CONTACT_ADDRESS_1,EMP_CONTACT_ADDRESS_2,EMP_CONTACT_CITY,EMP_CONTACT_STATE_PROVINCE,EMP_CONTACT_COUNTRY,EMP_CONTACT_POSTAL_CODE,EMP_CONTACT_PHONE,EMP_CONTACT_EMAIL,AGENT_ATTORNEY_NAME,AGENT_ATTORNEY_FIRM_NAME,AGENT_ATTORNEY_PHONE,AGENT_ATTORNEY_PHONE_EXT,AGENT_ATTORNEY_ADDRESS_1,AGENT_ATTORNEY_ADDRESS_2,AGENT_ATTORNEY_CITY,AGENT_ATTORNEY_STATE_PROVINCE,AGENT_ATTORNEY_COUNTRY,AGENT_ATTORNEY_POSTAL_CODE,AGENT_ATTORNEY_EMAIL,PW_TRACK_NUMBER,PW_SOC_CODE,PW_SOC_TITLE,PW_SKILL_LEVEL,PW_WAGE,PW_UNIT_OF_PAY,PW_WAGE_SOURCE,PW_SOURCE_NAME_OTHER,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_TO,WAGE_OFFER_UNIT_OF_PAY,WORKSITE_ADDRESS_1,WORKSITE_ADDRESS_2,WORKSITE_CITY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,JOB_TITLE,MINIMUM_EDUCATION,JOB_EDUCATION_MIN_OTHER,MAJOR_FIELD_OF_STUDY,REQUIRED_TRAINING,REQUIRED_TRAINING_MONTHS,REQUIRED_FIELD_OF_TRAINING,REQUIRED_EXPERIENCE,REQUIRED_EXPERIENCE_MONTHS,ACCEPT_ALT_FIELD_OF_STUDY,ACCEPT_ALT_MAJOR_FLD_OF_STUDY,ACCEPT_ALT_COMBO,ACCEPT_ALT_COMBO_EDUCATION,ACCEPT_ALT_COMBO_ED_OTHER,ACCEPT_ALT_COMBO_EDUCATION_YRS,ACCEPT_FOREIGN_EDUCATION,ACCEPT_ALT_OCCUPATION,ACCEPT_ALT_OCCUPATION_MONTHS,ACCEPT_ALT_JOB_TITLE,JOB_OPP_REQUIREMENTS_NORMAL,FOREIGN_LANGUAGE_REQUIRED,SPECIFIC_SKILLS,COMBINATION_OCCUPATION,OFFERED_TO_APPL_FOREIGN_WORKER,FOREIGN_WORKER_LIVE_ON_PREM,FOREIGN_WORKER_LIVE_IN_DOM_SER,FOREIGN_WORKER_LIVE_IN_DOM_SVC_CNT,PROFESSIONAL_OCCUPATION,APP_FOR_COLLEGE_U_TEACHER,COMPETITIVE_PROCESS,BASIC_RECRUITMENT_PROCESS,TEACHER_SELECT_DATE,TEACHER_PUB_JOURNAL_NAME,ADD_RECRUIT_INFORMATION,SWA_JOB_ORDER_START_DATE,SWA_JOB_ORDER_END_DATE,SUNDAY_EDITION_NEWSPAPER,FIRST_NEWSPAPER_NAME,FIRST_ADVERTISEMENT_START_DATE,SECOND_NEWSPAPER_AD_NAME,SECOND_ADVERTISEMENT_TYPE,SECOND_AD_START_DATE,JOB_FAIR_FROM_DATE,JOB_FAIR_TO_DATE,ON_CAMPUS_RECRUITING_FROM_DATE,ON_CAMPUS_RECRUITING_TO_DATE,EMPLOYER_WEBSITE_FROM_DATE,EMPLOYER_WEBSITE_TO_DATE,PRO_ORG_AD_FROM_DATE,PRO_ORG_ADVERTISEMENT_TO_DATE,JOB_SEARCH_WEBSITE_FROM_DATE,JOB_SEARCH_WEBSITE_TO_DATE,PVT_EMPLOYMENT_FIRM_FROM_DATE,PVT_EMPLOYMENT_FIRM_TO_DATE,EMPLOYEE_REF_PROG_FROM_DATE,EMPLOYEE_REFERRAL_PROG_TO_DATE,CAMPUS_PLACEMENT_FROM_DATE,CAMPUS_PLACEMENT_TO_DATE,LOCAL_ETHNIC_PAPER_FROM_DATE,LOCAL_ETHNIC_PAPER_TO_DATE,RADIO_TV_AD_FROM_DATE,RADIO_TV_AD_TO_DATE,EMP_RECEIVED_PAYMENT,PAYMENT_DETAILS,BARGAINING_REP_NOTIFIED,POSTED_NOTICE_AT_WORKSITE,LAYOFF_IN_PAST_SIX_MONTHS,US_WORKERS_CONSIDERED,COUNTRY_OF_CITIZENSHIP,FOREIGN_WORKER_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_EDUCATION,FOREIGN_WORKER_EDUCATION_OTHER,FOREIGN_WORKER_INFO_MAJOR,FOREIGN_WORKER_YRS_ED_COMP,FOREIGN_WORKER_INST_OF_ED,FOREIGN_WORKER_ED_INST_ADD_1,FOREIGN_WORKER_ED_INST_ADD_2,FOREIGN_WORKER_ED_INST_CITY,FOREIGN_WORKER_ED_INST_STATE_P,FOREIGN_WORKER_ED_INST_COUNTRY,FOREIGN_WORKER_ED_INST_POST_CD,FOREIGN_WORKER_TRAINING_COMP,FOREIGN_WORKER_REQ_EXPERIENCE,FOREIGN_WORKER_ALT_ED_EXP,FOREIGN_WORKER_ALT_OCC_EXP,FOREIGN_WORKER_EXP_WITH_EMPL,FOREIGN_WORKER_EMPL_PAY_FOR_ED,FOREIGN_WORKER_CURR_EMPLOYED,EMPLOYER_COMPLETED_APPLICATION,PREPARER_NAME,PREPARER_TITLE,PREPARER_EMAIL,EMP_INFO_DECL_NAME,EMP_DECL_TITLE
0,A-22262-24149,Withdrawn,2022-10-02,2022-10-02,N,NaT,NaN,N,Westgate Shellworld Inc,7012 Muncipal Drive,NaN,Orlando,FLORIDA,UNITED STATES OF AMERICA,32819,4074475040,NaN,45,1988.0,453220,N,Samia Ahmed,7012 Municipal Drive,NaN,Orlando,FLORIDA,UNITED STATES OF AMERICA,32819,4074475040 122,sahmed@oceanairenterprises.com,FRANCES DELAFUENTE,DELAFUENTE LAW LLC,7862929030,NaN,3105 NW 107 AVENUE,SUITE 400 G-2,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33172,MICHELLE@DLGPA.COM,P10021356781640,41-2031.00,RETAIL SALESPERSONS,Level I,20758.0,Year,OES,NaN,2022-06-21,2022-09-20,22880.0,NaN,Year,5870 US HWY 192,NaN,KISSIMMEE,FLORIDA,34746,SALES CLERK,NaN,NaN,NaN,N,NaN,NaN,N,NaN,N,NaN,N,NaN,NaN,NaN,N,N,NaN,NaN,Y,N,NONE,N,Y,N,N,NaN,N,N,NaN,NaN,NaT,NaN,NaN,2022-07-20,2022-08-24,Y,ORLANDO SENTINEL,2022-07-24,ORLANDO SENTINEL,Newspaper,2022-07-31,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,N,NaN,NaN,Y,N,NaN,NICARAGUA,NICARAGUA,NaN,High School,NaN,HIGH SCHOOL DIPLOMA,2010.0,INSTITUTO PUBLICO DE YALAGUINA,"DEL POLIDEPORTIVO MUNICIPAL, 400 MTRS. AL SURO...",NaN,SOMOTO,MADRIZ,NICARAGUA,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,FRANCES DELAFUENTE,ATTORNEY,MICHELLE@DLGPA.COM,SAMIA AHMED,OWNER
1,A-21187-12839,Certified-Expired,2022-02-03,2022-10-03,N,NaT,NaN,N,"NIKE, INC.",ONE BOWERMAN DRIVE,NaN,BEAVERTON,OREGON,UNITED STATES OF AMERICA,97005,503-671-6453,NaN,35000,1969.0,316210,N,Diana L Loveless,One Bowerman Drive,NaN,Beaverton,OREGON,UNITED STATES OF AMERICA,97005,503-532-3394,Diana.Loveless@nike.com,Chad T Li,Berry Appleman Leiden LLP,4697931827,NaN,"2400 N Glenville Drive, Building A",Suite 100,Richardson,TEXAS,UNITED STATES OF AMERICA,75082,chad.li@BAL.com,P10021127296744,11-2021,Marketing Managers,Level IV,167378.0,Year,OES,NaN,2021-10-21,2022-06-30,167378.0,NaN,Year,One Bowerman Dr.,NaN,Beaverton,OREGON,97005,Digital Services and Experiences Manager- Asia...,Master's,NaN,See H.14,N,NaN,NaN,Y,36.0,N,NaN,N,NaN,NaN,NaN,Y,Y,36.0,See H.14,N,N,Employer will accept Masters degree in Busines...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-11-22,2021-12-23,Y,The Oregonian,2021-12-05,The Oregonian,Newspaper,2021-12-12,NaT,NaT,NaT,NaT,2021-11-16,2021-12-23,NaT,NaT,2021-12-06,2021-12-13,NaT,NaT,NaT,NaT,NaT,NaT,2021-12-07,2021-12-10,NaT,NaT,N,NaN,NaN,Y,N,NaN,THAILAND,THAILAND,L-1,Master's,NaN,BUSINESS ADMINISTRATION,2008.0,SIAM UNIVERSITY,"38 PETCHKASEM RD, BANG WA, KHET PHASI CHAROEN",KRUNG THEP MAHA NAKHON,BANGKOK,NaN,THAILAND,10160,NaN,N,NaN,Y,N,N,Y,N,Chad T Li,Associate Attorney,chad.li@BAL.com,Diana Loveless,Immigration Program Consultant
2,A-21327-77110,Denied,2021-11-30,2022-10-03,N,NaT,NaN,N,RIVERY TECHNOLOGIES INC,500 7TH AVENUE,6TH FLOOR,NEW YORK,NEW YORK,UNITED STATES OF AMERICA,10018,212-671-0853,NaN,26,2019.0,54199,N,Michal Tshukati,500 7th Avenue,6th Floor,New York,NEW YORK,UNITED STATES OF AMERICA,10018,212-671-0853,suppliers@rivery.io,Rakhel S Milstein,Milstein Law Group PLLC,2129811981,NaN,"61 Broadway, Suite 2824",NaN,New York,NEW YORK,UNITED STATES OF AMERICA,10006,rsm@milsteinlg.com,P10021025032043,11-2021,Chief Executive Officer,Level IV,224307.0,Year,OES,NaN,2021-06-07,2021-09-05,224307.0,NaN,Year,500 7th Avenue,6th Floor,New York,NEW YORK,10018,Chief Executive Officer,Bachelor's,NaN,"Information Systems, Computer Engineering, or ...",N,NaN,NaN,N,NaN,N,NaN,N,NaN,NaN,NaN,Y,Y,120.0,Chief Executive Officer of a business intellig...,Y,N,Must have a Bachelors Degree in Information Sy...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-07-30,2021-09-02,Y,The New York Post,2021-08-15,The New York Post,Newspaper,2021-08-22,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2021-08-18,2021-09-16,NaT,NaT,NaT,NaT,NaT,NaT,2021-08-18,2021-08-18,2021-08-21,2021-08-21,N,NaN,NaN,Y,N,NaN,ISRAEL,ISRAEL,E-2,Bachelor's,NaN,INFORMATION SYSTEMS ENGINEERING,2002.0,BEN GURION UNIVERSITY OF THE NEGEV,1 BEN GURION AVENUE,NaN,BEER SHEVA,NEGEV,ISRAEL,8499000,NaN,NaN,NaN,Y,N,N,Y,N,Rakhel S Milstein,Attorney,rsm@milsteinlg.com,Aviv Noy,CoFounder
3,A-21342-83195,Certified-Expired,2022-02-03,2022-10-03,N,NaT,NaN,N,ESRI INC.,380 NEW YORK ST.,NaN,REDLANDS,CALIFORNIA,UNITED STATES OF AMERICA,92373,9097932853,NaN,4000,1969.0,511210,N,Vinesh Patel,380 New York St.,NaN,Redlands,CALIFORNIA,UNITED STATES OF AMERICA,92373,9097932853,vinesh_patel@esri.com,Jessica L Cross,"Ogletree, Deakins, Nash, Smoak Stewart, PC",2022630162,NaN,"1909 K Street, N.W.",Suite 1000,Washington,DISTRICT OF COLUMBIA,UNITED STATES OF AMERICA,20006,jessica.cross@ogletree.com,P10021137319941,11-2021,Marketing Managers,Level III,135990.0,Year,OES,NaN,2021-10-28,2022-06-30,135990.0,NaN,Year,55 Miracle Mile,Suite 250,Coral Gables,FLORIDA,33134,Business Development Manager,Master's,NaN,Business Administration,N,NaN,NaN,Y,36.0,Y,"Engineering any field, GIS, or related field o...",N,NaN,NaN,NaN,Y,Y,36.0,job offered or related occupation,Y,N,Applicants must have demonstrated experience w...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-10-28,2021-11-30,Y,Miami Herald,2021-12-19,Miami Herald,Newspaper,2021-12-26,NaT,NaT,NaT,NaT,2021-10-29,2021-11-12,NaT,NaT,2021-12-19,2022-01-02,NaT,NaT,NaT,NaT,NaT,NaT,2021-12-23,2021-12-29,NaT,NaT,N,NaN,NaN,Y,N,NaN,CANADA,COLOMBIA,H-1B,Master's,NaN,CIVIL ENGINEERING,2014.0,RYERSON UNIVERSITY,350 VICTORIA ST,NaN,TORONTO,ONTARIO,CANADA,M5B 2K3,NaN,N,NaN,Y,N,N,Y,N,Jessica L Cross,Attorney,jessica.cross@ogletree.com,Vinesh Patel,Global Mobility Coordinator
4,A-21349-86725,Certified-Expired,2022-02-03,2022-10-03,N,NaT,NaN,N,INGURAN LLC DBA STGENETICS,22575 STATE HWY 6 SOUTH,NaN,NAVASOTA,TEXAS,UNITED STATES OF AMERICA,77868,936-870-3960,199,666,2002.0,115210,N,Hayley R Harris,22575 State Hwy 6 South,NaN,Navasota,TEXAS,UNITED STATES OF AMERICA,77808,936-870-3960 198,hayley.harris@stgen.com,Beatriz Trillos Ballerini,"Trillos Ballerini Law Firm, P.C.",7137397272,NaN,3000 Weslayan Street,Suite 210,Houston,TEXAS,UNITED STATES OF AMERICA,77027,perm@tbvisas.com,P10021040066303,11-2021,Marketing Managers,Level IV,179754.0,Year,OES,NaN,2021-06-30,2021-09-28,179754.0,NaN,Year,22575 State Highway 6 South,NaN,Navasota,TEXAS,77868,"Business Development Manager Asia, Oceania, Mi...",Master's,NaN,Business Administration,N,NaN,NaN,Y,60.0,Y,Marketing or Veterinary Medicine,N,NaN,NaN,NaN,Y,N,NaN,NaN,Y,N,60 MONTHS OF EMPLOYMENT EXPERIENCE AS A MARKET...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaT,NaN,NaN,2021-08-24,2021-09-24,Y,The Eagle,2021-09-05,The Eagle,Newspaper,2021-09-12,NaT,NaT,NaT,NaT,NaT,NaT,2021-09-02,2021-10-01,2021-08-31,2021-09-30,NaT,NaT,NaT,NaT,NaT,NaT,2021-09-09,2021-09-15,NaT,NaT,N,NaN,NaN,Y,N,NaN,UNITED KINGDOM,INDIA,Not in USA,Master's,NaN,BUSINESS ADMINISTRATION,2005.0,UNIVERSITY OF BIRMINGHAM,EDGBASTON,NaN,BIRMINGHAM,NaN,UNITED KINGDOM,B15 2TT,NaN,Y,NaN,NaN,N,N,Y,N,Beatriz Trillos Ballerini,Attorney,perm@tbvisas.com,Steven Sfamenos,Human Resources Director

In [292]:
df.shape

(25000, 154)

In [293]:
# Show summary statistics for numerical columns
df.describe()

,RECEIVED_DATE,DECISION_DATE,ORIG_FILE_DATE,EMPLOYER_NUM_EMPLOYEES,EMPLOYER_YEAR_COMMENCED_BUSINESS,AGENT_ATTORNEY_PHONE_EXT,PW_WAGE,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_TO,REQUIRED_TRAINING_MONTHS,REQUIRED_EXPERIENCE_MONTHS,ACCEPT_ALT_COMBO_EDUCATION_YRS,ACCEPT_ALT_OCCUPATION_MONTHS,TEACHER_SELECT_DATE,SWA_JOB_ORDER_START_DATE,SWA_JOB_ORDER_END_DATE,FIRST_ADVERTISEMENT_START_DATE,SECOND_AD_START_DATE,JOB_FAIR_FROM_DATE,JOB_FAIR_TO_DATE,ON_CAMPUS_RECRUITING_FROM_DATE,ON_CAMPUS_RECRUITING_TO_DATE,EMPLOYER_WEBSITE_FROM_DATE,EMPLOYER_WEBSITE_TO_DATE,PRO_ORG_AD_FROM_DATE,PRO_ORG_ADVERTISEMENT_TO_DATE,JOB_SEARCH_WEBSITE_FROM_DATE,JOB_SEARCH_WEBSITE_TO_DATE,PVT_EMPLOYMENT_FIRM_FROM_DATE,PVT_EMPLOYMENT_FIRM_TO_DATE,EMPLOYEE_REF_PROG_FROM_DATE,EMPLOYEE_REFERRAL_PROG_TO_DATE,CAMPUS_PLACEMENT_FROM_DATE,CAMPUS_PLACEMENT_TO_DATE,LOCAL_ETHNIC_PAPER_FROM_DATE,LOCAL_ETHNIC_PAPER_TO_DATE,RADIO_TV_AD_FROM_DATE,RADIO_TV_AD_TO_DATE,FOREIGN_WORKER_YRS_ED_COMP
count,25000,25000,8,2.500000e+04,24999.000000,502.000000,24992.000000,24988,24988,2.500000e+04,9469.000000,255.000000,13952.000000,6418.000000,16939.000000,235,24752,24752,24752,24752,18,18,106,106,10415,10415,3589,3589,19351,19351,737,737,5925,5925,1928,1928,15224,15224,3212,3212,21755.000000
mean,2022-02-21 17:00:16.128000,2022-11-17 01:49:19.488000,2017-04-24 12:00:00,7.701520e+04,1987.280451,1152.842629,89749.249462,2021-10-09 18:47:32.569233152,2022-05-22 03:47:41.213382400,1.013162e+05,155355.323248,29.988235,29.294438,4.791680,32.774603,2021-07-12 16:20:25.531915008,2021-10-16 13:18:11.402715136,2021-11-21 11:24:58.642534144,2021-10-28 20:35:09.502262528,2021-11-05 01:36:27.459599104,2021-07-28 00:00:00,2021-07-28 06:40:00,2021-10-14 14:29:26.037735936,2021-10-25 19:01:07.924528384,2021-11-05 09:50:22.755640832,2021-12-06 18:17:56.370619136,2021-10-31 11:52:10.565616896,2021-11-13 10:23:30.309278464,2021-10-29 20:56:56.381582336,2021-11-16 14:22:50.347785728,2021-11-16 23:22:52.591587584,2021-12-01 16:20:50.474898176,2021-10-24 09:26:31.291139328,2021-11-15 07:46:52.556962048,2021-11-03 02:36:05.975103744,2021-11-23 00:27:38.091286528,2021-11-04 11:54:19.485023488,2021-11-07 02:11:56.973200128,2021-11-22 01:37:17.110834432,2021-11-22 12:08:04.184308480,2008.133533
min,2016-07-13 00:00:00,2022-10-02 00:00:00,2012-04-04 00:00:00,0.000000e+00,1646.000000,1.000000,8.000000,2000-07-09 00:00:00,1930-12-02 00:00:00,8.000000e+00,10.000000,0.000000,0.000000,0.000000,0.000000,2020-05-05 00:00:00,2002-01-05 00:00:00,2000-12-31 00:00:00,2016-03-06 00:00:00,2016-03-13 00:00:00,2017-04-08 00:00:00,2017-04-08 00:00:00,2016-12-13 00:00:00,2017-01-19 00:00:00,2016-02-01 00:00:00,2016-06-08 00:00:00,2017-11-13 00:00:00,2017-12-12 00:00:00,2002-01-25 00:00:00,2016-06-08 00:00:00,2018-08-06 00:00:00,2018-08-21 00:00:00,2016-05-08 00:00:00,2016-06-08 00:00:00,2016-11-02 00:00:00,2017-07-14 00:00:00,2000-01-01 00:00:00,2000-01-01 00:00:00,2017-06-14 00:00:00,2017-06-14 00:00:00,0.000000
25%,2022-02-03 00:00:00,2022-10-27 00:00:00,2015-08-22 18:00:00,1.200000e+02,1977.000000,104.000000,60570.000000,2021-08-20 00:00:00,2022-06-30 00:00:00,6.905775e+04,130000.000000,6.000000,12.000000,4.000000,12.000000,2021-02-28 00:00:00,2021-09-09 00:00:00,2021-10-13 00:00:00,2021-09-19 00:00:00,2021-09-26 00:00:00,2021-08-31 00:00:00,2021-08-31 00:00:00,2021-10-04 00:00:00,2021-10-04 00:00:00,2021-09-30 00:00:00,2021-10-21 00:00:00,2021-10-01 00:00:00,2021-10-06 00:00:00,2021-09-21 00:00:00,2021-10-05 00:00:00,2021-11-10 00:00:00,2021-11-22 00:00:00,2021-08-19 00:00:00,2021-09-10 00:00:00,2021-09-29 00:00:00,2021-10-19 00:00:00,2021-09-24 00:00:00,2021-09-24 00:00:00,2021-10-12 00:00:00,2021-10-12 18:00:00,2008.000000
50%,2022-02-25 00:00:00,2022-11-18 00:00:00,2017-06-19 00:00:00,2.432000e+03,1997.000000,201.000000,93558.000000,2021-10-19 00:00:00,2022-06-30 00:00:00,1.026460e+05,160000.000000,36.000000,24.000000,5.000000,24.000000,2021-06-29 00:00:00,2021-10-20 00:00:00,2021-11-23 00:00:00,2021-10-31 00:00:00,2021-11-07 00:00:00,2021-09-28 12:00:00,2021-10-01 00:00:00,2021-10-04 00:00:00,2021-10-04 00:00:00,2021-11-05 00:00:00,2021-12-06 00:00:00,2021-11-05 00:00:00,2021-11-24 00:00:00,2021-10-31 00:00:00,2021-11-17 00:00:00,2021-11-15 00:00:00,2021-11-22 00:00:00,2021-10-22 00:00:00,2021-11-16 00:00:00,2021-11-03 00:00:00,2021-11-22 00:00:00,2021-11-04 00:00:00,2021-11-04 00:00:00,2021-11-18 00:00:00,2021-11-18 00:00:00,2014.000000
75%,2022-03-23 00:00:00,2022-12-12 00:00:00,2019-02-14 12:00:00,3.500000e+04,2009.000000,226.000000,119350.000000,2021-12-10 00:00:00,2022-06-30 00:00:00,1.316850e+05,185000.000000,36.000000,36.000000,5.000000,60.000000,2022-01-14 12:00:00,2021-12-01 00:00:00,2022-01-04 00:00:00,2021-12-12 00:00:00,2021-12-19 00:00:00,2022-01-09 18:00:00,2022-01-09 18:00:00,2021-11-07 06:00:00,2021-12-07 12:00:00,2021-12-10 00:00:00,2022-01-15 00:00:00,2022-01-01 00:00:00,2022-01-03 00:00:00,2021-12-13 00:00:00,2022-01-02 00:00:00,2021-11-19 00:00:00,2021-12-11 00:00:00,2021-12-07 00:00:00,2022-01-04 00:00:00,2021-12-13 00:00:00,2022-01-03 00:00:00,2021-12-20 00:00:00,2021-12-22 00:00:00,2021-12-28 00:00:00,2021-12-29 00:00:00,2017.000000
max,2022-12-28 00:00:00,2022-12-28 00:00:00,2022-02-02 00:00:00,3.000000e+06,2022.000000,85194.000000,637000.000000,2025-02-04 00:00:00,2028-03-01 00:00:00,1.650000e+06,920000.000000,108.000000,180.000000,96.000000,180.000000,2022-10-20 00:00:00,2023-04-03 00:00:00,2029-02-26 00:00:00,2022-11-11 00:00:00,2022-11-13 00:00:00,2022-09-20 00:00:00,2022-09-20 00:00:00,2022-09-22 00:00:00,2022-09-28 00:00:00,2022-11-02 00:00:00,2022-12-06 00:00:00,2022-10-17 00:00:00,2022-10-24 00:00:00,2022-11-06 00:00:00,2022-12-05 00:00:00,2022-10-28 00:00:00,2022-11-12 00:00:00,2022-11-28 00:00:00,2022-12-19 00:00:00,2022-10-11 00:00:00,2022-11-04 00:00:00,2022-11-10 00:00:00,2022-11-10 00:00:00,2022-11-10 00:00:00,2022-11-10 00:00:00,2022.000000
std,NaN,NaN,NaN,2.087317e+05,36.718271,6086.521712,42821.995854,NaN,NaN,5.864185e+04,65123.257825,21.468982,21.846344,5.126975,22.966292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.550768

In [294]:
# Show percentage of missing values in each column
print(df.isnull().mean() * 100)

CASE_NUMBER                            0.000
CASE_STATUS                            0.000
RECEIVED_DATE                          0.000
DECISION_DATE                          0.000
REFILE                                 0.000
ORIG_FILE_DATE                        99.968
PREVIOUS_SWA_CASE_NUMBER_STATE        99.968
SCHD_A_SHEEPHERDER                     0.000
EMPLOYER_NAME                          0.000
EMPLOYER_ADDRESS_1                     0.000
EMPLOYER_ADDRESS_2                    70.940
EMPLOYER_CITY                          0.000
EMPLOYER_STATE_PROVINCE                0.000
EMPLOYER_COUNTRY                       0.000
EMPLOYER_POSTAL_CODE                   0.000
EMPLOYER_PHONE                         0.004
EMPLOYER_PHONE_EXT                    93.152
EMPLOYER_NUM_EMPLOYEES                 0.000
EMPLOYER_YEAR_COMMENCED_BUSINESS       0.004
NAICS_CODE                             0.068
FW_OWNERSHIP_INTEREST                  0.000
EMP_CONTACT_NAME                       0.000
EMP_CONTACT_ADDRESS_1                  0.000
EMP_CONTACT_ADDRESS_2                 64.912
EMP_CONTACT_CITY                       0.000
EMP_CONTACT_STATE_PROVINCE             0.000
EMP_CONTACT_COUNTRY                    0.004
EMP_CONTACT_POSTAL_CODE                0.000
EMP_CONTACT_PHONE                      0.000
EMP_CONTACT_EMAIL                      0.000
AGENT_ATTORNEY_NAME                    0.000
AGENT_ATTORNEY_FIRM_NAME               9.692
AGENT_ATTORNEY_PHONE                   8.356
AGENT_ATTORNEY_PHONE_EXT              97.992
AGENT_ATTORNEY_ADDRESS_1               8.352
AGENT_ATTORNEY_ADDRESS_2              33.196
AGENT_ATTORNEY_CITY                    8.352
AGENT_ATTORNEY_STATE_PROVINCE          9.392
AGENT_ATTORNEY_COUNTRY                 8.344
AGENT_ATTORNEY_POSTAL_CODE             8.384
AGENT_ATTORNEY_EMAIL                   8.380
PW_TRACK_NUMBER                        0.308
PW_SOC_CODE                            0.048
PW_SOC_TITLE                           0.036
PW_SKILL_LEVEL                         5.804
PW_WAGE                                0.032
PW_UNIT_OF_PAY                         0.032
PW_WAGE_SOURCE                         0.036
PW_SOURCE_NAME_OTHER                  94.864
PW_DETERMINATION_DATE                  0.048
PW_EXPIRATION_DATE                     0.048
WAGE_OFFER_FROM                        0.000
WAGE_OFFER_TO                         62.124
WAGE_OFFER_UNIT_OF_PAY                 0.004
WORKSITE_ADDRESS_1                     0.000
WORKSITE_ADDRESS_2                    63.356
WORKSITE_CITY                          0.000
WORKSITE_STATE                         0.000
WORKSITE_POSTAL_CODE                   0.000
JOB_TITLE                              0.004
MINIMUM_EDUCATION                     14.384
JOB_EDUCATION_MIN_OTHER               97.408
MAJOR_FIELD_OF_STUDY                  19.468
REQUIRED_TRAINING                      0.000
REQUIRED_TRAINING_MONTHS              98.980
REQUIRED_FIELD_OF_TRAINING            98.972
REQUIRED_EXPERIENCE                    0.000
REQUIRED_EXPERIENCE_MONTHS            44.192
ACCEPT_ALT_FIELD_OF_STUDY              0.004
ACCEPT_ALT_MAJOR_FLD_OF_STUDY         57.204
ACCEPT_ALT_COMBO                       0.004
ACCEPT_ALT_COMBO_EDUCATION            75.572
ACCEPT_ALT_COMBO_ED_OTHER             98.696
ACCEPT_ALT_COMBO_EDUCATION_YRS        74.328
ACCEPT_FOREIGN_EDUCATION               0.004
ACCEPT_ALT_OCCUPATION                  0.000
ACCEPT_ALT_OCCUPATION_MONTHS          32.244
ACCEPT_ALT_JOB_TITLE                  32.244
JOB_OPP_REQUIREMENTS_NORMAL            0.000
FOREIGN_LANGUAGE_REQUIRED              0.000
SPECIFIC_SKILLS                       11.556
COMBINATION_OCCUPATION                 0.000
OFFERED_TO_APPL_FOREIGN_WORKER         0.000
FOREIGN_WORKER_LIVE_ON_PREM            0.000
FOREIGN_WORKER_LIVE_IN_DOM_SER         0.000
FOREIGN_WORKER_LIVE_IN_DOM_SVC_CNT    99.888
PROFESSIONAL_OCCUPATION                0.004
APP_FOR_COLLEGE_U_TEACHER              0.004
COMPETITIVE_PROCESS                   98.828
BASIC_RECRUITMENT_PROCESS             98.832
TEACHER_SELECT_DATE                   99.060
TEACHER_PUB_JOURNAL_NAME              99.056
ADD_RECRUIT_INFORMATION               99.152
SWA_JOB_ORDER_START_DATE               0.992
SWA_JOB_ORDER_END_DATE                 0.992
SUNDAY_EDITION_NEWSPAPER               0.992
FIRST_NEWSPAPER_NAME                   1.012
FIRST_ADVERTISEMENT_START_DATE         0.992
SECOND_NEWSPAPER_AD_NAME               1.012
SECOND_ADVERTISEMENT_TYPE              0.992
SECOND_AD_START_DATE                   0.992
JOB_FAIR_FROM_DATE                    99.928
JOB_FAIR_TO_DATE                      99.928
ON_CAMPUS_RECRUITING_FROM_DATE        99.576
ON_CAMPUS_RECRUITING_TO_DATE          99.576
EMPLOYER_WEBSITE_FROM_DATE            58.340
EMPLOYER_WEBSITE_TO_DATE              58.340
PRO_ORG_AD_FROM_DATE                  85.644
PRO_ORG_ADVERTISEMENT_TO_DATE         85.644
JOB_SEARCH_WEBSITE_FROM_DATE          22.596
JOB_SEARCH_WEBSITE_TO_DATE            22.596
PVT_EMPLOYMENT_FIRM_FROM_DATE         97.052
PVT_EMPLOYMENT_FIRM_TO_DATE           97.052
EMPLOYEE_REF_PROG_FROM_DATE           76.300
EMPLOYEE_REFERRAL_PROG_TO_DATE        76.300
CAMPUS_PLACEMENT_FROM_DATE            92.288
CAMPUS_PLACEMENT_TO_DATE              92.288
LOCAL_ETHNIC_PAPER_FROM_DATE          39.104
LOCAL_ETHNIC_PAPER_TO_DATE            39.104
RADIO_TV_AD_FROM_DATE                 87.152
RADIO_TV_AD_TO_DATE                   87.152
EMP_RECEIVED_PAYMENT                   0.004
PAYMENT_DETAILS                       99.996
BARGAINING_REP_NOTIFIED               97.060
POSTED_NOTICE_AT_WORKSITE              0.708
LAYOFF_IN_PAST_SIX_MONTHS              0.004
US_WORKERS_CONSIDERED                 95.508
COUNTRY_OF_CITIZENSHIP                 0.004
FOREIGN_WORKER_BIRTH_COUNTRY           0.008
CLASS_OF_ADMISSION                    10.200
FOREIGN_WORKER_EDUCATION              12.956
FOREIGN_WORKER_EDUCATION_OTHER        97.184
FOREIGN_WORKER_INFO_MAJOR             14.168
FOREIGN_WORKER_YRS_ED_COMP            12.980
FOREIGN_WORKER_INST_OF_ED             13.096
FOREIGN_WORKER_ED_INST_ADD_1          14.160
FOREIGN_WORKER_ED_INST_ADD_2          89.248
FOREIGN_WORKER_ED_INST_CITY           13.292
FOREIGN_WORKER_ED_INST_STATE_P        19.876
FOREIGN_WORKER_ED_INST_COUNTRY        13.788
FOREIGN_WORKER_ED_INST_POST_CD        16.720
FOREIGN_WORKER_TRAINING_COMP          98.684
FOREIGN_WORKER_REQ_EXPERIENCE         43.952
FOREIGN_WORKER_ALT_ED_EXP             76.808
FOREIGN_WORKER_ALT_OCC_EXP            32.624
FOREIGN_WORKER_EXP_WITH_EMPL          20.796
FOREIGN_WORKER_EMPL_PAY_FOR_ED         0.004
FOREIGN_WORKER_CURR_EMPLOYED           0.008
EMPLOYER_COMPLETED_APPLICATION         0.028
PREPARER_NAME                          0.000
PREPARER_TITLE                         8.976
PREPARER_EMAIL                         9.028
EMP_INFO_DECL_NAME                     0.004
EMP_DECL_TITLE                         0.008
dtype: float64

 ## Handling Missing Values

In [295]:
# Dropping columns with more than 50% missing values
threshold = 50 # percentage
high_missing = df.columns[df.isnull().mean() * 100 > threshold]
df.drop(columns=high_missing, inplace=True)

# Filling missing values for numeric columns with the median
for col in df.select_dtypes(include='number').columns:
    df[col].fillna(df[col].median(), inplace=True)

# Filling missing values for categorical columns with the mode
for col in df.select_dtypes(include='object').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

## Correcting Data Types

In [296]:
# Convert date columns to datetime
date_columns = ['RECEIVED_DATE', 'DECISION_DATE']  # Add or adjust according to your dataset
for date in date_columns:
    df[date] = pd.to_datetime(df[date])

# Convert categorical columns to 'category' data type if they have a limited number of unique values
for col in ['CASE_STATUS', 'REFILE', 'SCHD_A_SHEEPHERDER']:
    df[col] = df[col].astype('category')

## Removing Duplicates

In [297]:
# Drop duplicate rows
df.drop_duplicates(inplace=True)

# Check for duplicates based on a subset of columns (for example, 'CASE_NUMBER')
df.drop_duplicates(subset=['CASE_NUMBER'], inplace=True)

## Final Data Check

In [298]:
df.shape

(25000, 109)

In [299]:
# Review the cleaned dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Columns: 109 entries, CASE_NUMBER to EMP_DECL_TITLE
dtypes: category(3), datetime64[ns](12), float64(6), int64(1), object(87)
memory usage: 20.3+ MB
None

In [300]:
df.head()

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,REFILE,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,EMPLOYER_CITY,EMPLOYER_STATE_PROVINCE,EMPLOYER_COUNTRY,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,EMPLOYER_NUM_EMPLOYEES,EMPLOYER_YEAR_COMMENCED_BUSINESS,NAICS_CODE,FW_OWNERSHIP_INTEREST,EMP_CONTACT_NAME,EMP_CONTACT_ADDRESS_1,EMP_CONTACT_CITY,EMP_CONTACT_STATE_PROVINCE,EMP_CONTACT_COUNTRY,EMP_CONTACT_POSTAL_CODE,EMP_CONTACT_PHONE,EMP_CONTACT_EMAIL,AGENT_ATTORNEY_NAME,AGENT_ATTORNEY_FIRM_NAME,AGENT_ATTORNEY_PHONE,AGENT_ATTORNEY_ADDRESS_1,AGENT_ATTORNEY_ADDRESS_2,AGENT_ATTORNEY_CITY,AGENT_ATTORNEY_STATE_PROVINCE,AGENT_ATTORNEY_COUNTRY,AGENT_ATTORNEY_POSTAL_CODE,AGENT_ATTORNEY_EMAIL,PW_TRACK_NUMBER,PW_SOC_CODE,PW_SOC_TITLE,PW_SKILL_LEVEL,PW_WAGE,PW_UNIT_OF_PAY,PW_WAGE_SOURCE,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_UNIT_OF_PAY,WORKSITE_ADDRESS_1,WORKSITE_CITY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,JOB_TITLE,MINIMUM_EDUCATION,MAJOR_FIELD_OF_STUDY,REQUIRED_TRAINING,REQUIRED_EXPERIENCE,REQUIRED_EXPERIENCE_MONTHS,ACCEPT_ALT_FIELD_OF_STUDY,ACCEPT_ALT_COMBO,ACCEPT_FOREIGN_EDUCATION,ACCEPT_ALT_OCCUPATION,ACCEPT_ALT_OCCUPATION_MONTHS,ACCEPT_ALT_JOB_TITLE,JOB_OPP_REQUIREMENTS_NORMAL,FOREIGN_LANGUAGE_REQUIRED,SPECIFIC_SKILLS,COMBINATION_OCCUPATION,OFFERED_TO_APPL_FOREIGN_WORKER,FOREIGN_WORKER_LIVE_ON_PREM,FOREIGN_WORKER_LIVE_IN_DOM_SER,PROFESSIONAL_OCCUPATION,APP_FOR_COLLEGE_U_TEACHER,SWA_JOB_ORDER_START_DATE,SWA_JOB_ORDER_END_DATE,SUNDAY_EDITION_NEWSPAPER,FIRST_NEWSPAPER_NAME,FIRST_ADVERTISEMENT_START_DATE,SECOND_NEWSPAPER_AD_NAME,SECOND_ADVERTISEMENT_TYPE,SECOND_AD_START_DATE,JOB_SEARCH_WEBSITE_FROM_DATE,JOB_SEARCH_WEBSITE_TO_DATE,LOCAL_ETHNIC_PAPER_FROM_DATE,LOCAL_ETHNIC_PAPER_TO_DATE,EMP_RECEIVED_PAYMENT,POSTED_NOTICE_AT_WORKSITE,LAYOFF_IN_PAST_SIX_MONTHS,COUNTRY_OF_CITIZENSHIP,FOREIGN_WORKER_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_EDUCATION,FOREIGN_WORKER_INFO_MAJOR,FOREIGN_WORKER_YRS_ED_COMP,FOREIGN_WORKER_INST_OF_ED,FOREIGN_WORKER_ED_INST_ADD_1,FOREIGN_WORKER_ED_INST_CITY,FOREIGN_WORKER_ED_INST_STATE_P,FOREIGN_WORKER_ED_INST_COUNTRY,FOREIGN_WORKER_ED_INST_POST_CD,FOREIGN_WORKER_REQ_EXPERIENCE,FOREIGN_WORKER_ALT_OCC_EXP,FOREIGN_WORKER_EXP_WITH_EMPL,FOREIGN_WORKER_EMPL_PAY_FOR_ED,FOREIGN_WORKER_CURR_EMPLOYED,EMPLOYER_COMPLETED_APPLICATION,PREPARER_NAME,PREPARER_TITLE,PREPARER_EMAIL,EMP_INFO_DECL_NAME,EMP_DECL_TITLE
0,A-22262-24149,Withdrawn,2022-10-02,2022-10-02,N,N,Westgate Shellworld Inc,7012 Muncipal Drive,Orlando,FLORIDA,UNITED STATES OF AMERICA,32819,4074475040,45,1988.0,453220,N,Samia Ahmed,7012 Municipal Drive,Orlando,FLORIDA,UNITED STATES OF AMERICA,32819,4074475040 122,sahmed@oceanairenterprises.com,FRANCES DELAFUENTE,DELAFUENTE LAW LLC,7862929030,3105 NW 107 AVENUE,SUITE 400 G-2,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33172,MICHELLE@DLGPA.COM,P10021356781640,41-2031.00,RETAIL SALESPERSONS,Level I,20758.0,Year,OES,2022-06-21,2022-09-20,22880.0,Year,5870 US HWY 192,KISSIMMEE,FLORIDA,34746,SALES CLERK,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,2022-07-20,2022-08-24,Y,ORLANDO SENTINEL,2022-07-24,ORLANDO SENTINEL,Newspaper,2022-07-31,NaT,NaT,NaT,NaT,N,Y,N,NICARAGUA,NICARAGUA,H-1B,High School,HIGH SCHOOL DIPLOMA,2010.0,INSTITUTO PUBLICO DE YALAGUINA,"DEL POLIDEPORTIVO MUNICIPAL, 400 MTRS. AL SURO...",SOMOTO,MADRIZ,NICARAGUA,600025,N,Y,N,N,N,N,FRANCES DELAFUENTE,ATTORNEY,MICHELLE@DLGPA.COM,SAMIA AHMED,OWNER
1,A-21187-12839,Certified-Expired,2022-02-03,2022-10-03,N,N,"NIKE, INC.",ONE BOWERMAN DRIVE,BEAVERTON,OREGON,UNITED STATES OF AMERICA,97005,503-671-6453,35000,1969.0,316210,N,Diana L Loveless,One Bowerman Drive,Beaverton,OREGON,UNITED STATES OF AMERICA,97005,503-532-3394,Diana.Loveless@nike.com,Chad T Li,Berry Appleman Leiden LLP,4697931827,"2400 N Glenville Drive, Building A",Suite 100,Richardson,TEXAS,UNITED STATES OF AMERICA,75082,chad.li@BAL.com,P10021127296744,11-2021,Marketing Managers,Level IV,167378.0,Year,OES,2021-10-21,2022-06-30,167378.0,Year,One Bowerman Dr.,Beaverton,OREGON,97005,Digital Services and Experiences Manager- Asia...,Master's,See H.14,N,Y,36.0,N,N,Y,Y,36.0,See H.14,N,N,Employer will accept Masters degree in Busines...,N,Y,N,N,Y,N,2021-11-22,2021-12-23,Y,The Oregonian,2021-12-05,The Oregonian,Newspaper,2021-12-12,2021-12-06,2021-12-13,2021-12-07,2021-12-10,N,Y,N,THAILAND,THAILAND,L-1,Master's,BUSINESS ADMINISTRATION,2008.0,SIAM UNIVERSITY,"38 PETCHKASEM RD, BANG WA, KHET PHASI CHAROEN",BANGKOK,CA,THAILAND,10160,N,Y,N,N,Y,N,Chad T Li,Associate Attorney,chad.li@BAL.com,Diana Loveless,Immigration Program Consultant
2,A-21327-77110,Denied,2021-11-30,2022-10-03,N,N,RIVERY TECHNOLOGIES INC,500 7TH AVENUE,NEW YORK,NEW YORK,UNITED STATES OF AMERICA,10018,212-671-0853,26,2019.0,54199,N,Michal Tshukati,500 7th Avenue,New York,NEW YORK,UNITED STATES OF AMERICA,10018,212-671-0853,suppliers@rivery.io,Rakhel S Milstein,Milstein Law Group PLLC,2129811981,"61 Broadway, Suite 2824",3rd Floor,New York,NEW YORK,UNITED STATES OF AMERICA,10006,rsm@milsteinlg.com,P10021025032043,11-2021,Chief Executive Officer,Level IV,224307.0,Year,OES,2021-06-07,2021-09-05,224307.0,Year,500 7th Avenue,New York,NEW YORK,10018,Chief Executive Officer,Bachelor's,"Information Systems, Computer Engineering, or ...",N,N,24.0,N,N,Y,Y,120.0,Chief Executive Officer of a business intellig...,Y,N,Must have a Bachelors Degree in Information Sy...,N,Y,N,N,Y,N,2021-07-30,2021-09-02,Y,The New York Post,2021-08-15,The New York Post,Newspaper,2021-08-22,2021-08-18,2021-09-16,2021-08-18,2021-08-18,N,Y,N,ISRAEL,ISRAEL,E-2,Bachelor's,INFORMATION SYSTEMS ENGINEERING,2002.0,BEN GURION UNIVERSITY OF THE NEGEV,1 BEN GURION AVENUE,BEER SHEVA,NEGEV,ISRAEL,8499000,N,Y,N,N,Y,N,Rakhel S Milstein,Attorney,rsm@milsteinlg.com,Aviv Noy,CoFounder
3,A-21342-83195,Certified-Expired,2022-02-03,2022-10-03,N,N,ESRI INC.,380 NEW YORK ST.,REDLANDS,CALIFORNIA,UNITED STATES OF AMERICA,92373,9097932853,4000,1969.0,511210,N,Vinesh Patel,380 New York St.,Redlands,CALIFORNIA,UNITED STATES OF AMERICA,92373,9097932853,vinesh_patel@esri.com,Jessica L Cross,"Ogletree, Deakins, Nash, Smoak Stewart, PC",2022630162,"1909 K Street, N.W.",Suite 1000,Washington,DISTRICT OF COLUMBIA,UNITED STATES OF AMERICA,20006,jessica.cross@ogletree.com,P10021137319941,11-2021,Marketing Managers,Level III,135990.0,Year,OES,2021-10-28,2022-06-30,135990.0,Year,55 Miracle Mile,Coral Gables,FLORIDA,33134,Business Development Manager,Master's,Business Administration,N,Y,36.0,Y,N,Y,Y,36.0,job offered or related occupation,Y,N,Applicants must have demonstrated experience w...,N,Y,N,N,Y,N,2021-10-28,2021-11-30,Y,Miami Herald,2021-12-19,Miami Herald,Newspaper,2021-12-26,2021-12-19,2022-01-02,2021-12-23,2021-12-29,N,Y,N,CANADA,COLOMBIA,H-1B,Master's,CIVIL ENGINEERING,2014.0,RYERSON UNIVERSITY,350 VICTORIA ST,TORONTO,ONTARIO,CANADA,M5B 2K3,N,Y,N,N,Y,N,Jessica L Cross,Attorney,jessica.cross@ogletree.com,Vinesh Patel,Global Mobility Coordinator
4,A-21349-86725,Certified-Expired,2022-02-03,2022-10-03,N,N,INGURAN LLC DBA STGENETICS,22575 STATE HWY 6 SOUTH,NAVASOTA,TEXAS,UNITED STATES OF AMERICA,77868,936-870-3960,666,2002.0,115210,N,Hayley R Harris,22575 State Hwy 6 South,Navasota,TEXAS,UNITED STATES OF AMERICA,77808,936-870-3960 198,hayley.harris@stgen.com,Beatriz Trillos Ballerini,"Trillos Ballerini Law Firm, P.C.",7137397272,3000 Weslayan Street,Suite 210,Houston,TEXAS,UNITED STATES OF AMERICA,77027,perm@tbvisas.com,P10021040066303,11-2021,Marketing Managers,Level IV,179754.0,Year,OES,2021-06-30,2021-09-28,179754.0,Year,22575 State Highway 6 South,Navasota,TEXAS,77868,"Business Development Manager Asia, Oceania, Mi...",Master's,Business Administration,N,Y,60.0,Y,N,Y,N,24.0,See H.14,Y,N,60 MONTHS OF EMPLOYMENT EXPERIENCE AS A MARKET...,N,Y,N,N,Y,N,2021-08-24,2021-09-24,Y,The Eagle,2021-09-05,The Eagle,Newspaper,2021-09-12,2021-08-31,2021-09-30,2021-09-09,2021-09-15,N,Y,N,UNITED KINGDOM,INDIA,Not in USA,Master's,BUSINESS ADMINISTRATION,2005.0,UNIVERSITY OF BIRMINGHAM,EDGBASTON,BIRMINGHAM,CA,UNITED KINGDOM,B15 2TT,Y,Y,N,N,Y,N,Beatriz Trillos Ballerini,Attorney,perm@tbvisas.com,Steven Sfamenos,Human Resources Director

## Show the columns and check again for the missing values

In [301]:
df.columns

Index(['CASE_NUMBER', 'CASE_STATUS', 'RECEIVED_DATE', 'DECISION_DATE',
       'REFILE', 'SCHD_A_SHEEPHERDER', 'EMPLOYER_NAME', 'EMPLOYER_ADDRESS_1',
       'EMPLOYER_CITY', 'EMPLOYER_STATE_PROVINCE',
       ...
       'FOREIGN_WORKER_ALT_OCC_EXP', 'FOREIGN_WORKER_EXP_WITH_EMPL',
       'FOREIGN_WORKER_EMPL_PAY_FOR_ED', 'FOREIGN_WORKER_CURR_EMPLOYED',
       'EMPLOYER_COMPLETED_APPLICATION', 'PREPARER_NAME', 'PREPARER_TITLE',
       'PREPARER_EMAIL', 'EMP_INFO_DECL_NAME', 'EMP_DECL_TITLE'],
      dtype='object', length=109)

In [302]:
# Show percentage of missing values in each column
print(df.isnull().mean() * 100)

CASE_NUMBER                          0.000
CASE_STATUS                          0.000
RECEIVED_DATE                        0.000
DECISION_DATE                        0.000
REFILE                               0.000
SCHD_A_SHEEPHERDER                   0.000
EMPLOYER_NAME                        0.000
EMPLOYER_ADDRESS_1                   0.000
EMPLOYER_CITY                        0.000
EMPLOYER_STATE_PROVINCE              0.000
EMPLOYER_COUNTRY                     0.000
EMPLOYER_POSTAL_CODE                 0.000
EMPLOYER_PHONE                       0.000
EMPLOYER_NUM_EMPLOYEES               0.000
EMPLOYER_YEAR_COMMENCED_BUSINESS     0.000
NAICS_CODE                           0.000
FW_OWNERSHIP_INTEREST                0.000
EMP_CONTACT_NAME                     0.000
EMP_CONTACT_ADDRESS_1                0.000
EMP_CONTACT_CITY                     0.000
EMP_CONTACT_STATE_PROVINCE           0.000
EMP_CONTACT_COUNTRY                  0.000
EMP_CONTACT_POSTAL_CODE              0.000
EMP_CONTACT_PHONE                    0.000
EMP_CONTACT_EMAIL                    0.000
AGENT_ATTORNEY_NAME                  0.000
AGENT_ATTORNEY_FIRM_NAME             0.000
AGENT_ATTORNEY_PHONE                 0.000
AGENT_ATTORNEY_ADDRESS_1             0.000
AGENT_ATTORNEY_ADDRESS_2             0.000
AGENT_ATTORNEY_CITY                  0.000
AGENT_ATTORNEY_STATE_PROVINCE        0.000
AGENT_ATTORNEY_COUNTRY               0.000
AGENT_ATTORNEY_POSTAL_CODE           0.000
AGENT_ATTORNEY_EMAIL                 0.000
PW_TRACK_NUMBER                      0.000
PW_SOC_CODE                          0.000
PW_SOC_TITLE                         0.000
PW_SKILL_LEVEL                       0.000
PW_WAGE                              0.000
PW_UNIT_OF_PAY                       0.000
PW_WAGE_SOURCE                       0.000
PW_DETERMINATION_DATE                0.048
PW_EXPIRATION_DATE                   0.048
WAGE_OFFER_FROM                      0.000
WAGE_OFFER_UNIT_OF_PAY               0.000
WORKSITE_ADDRESS_1                   0.000
WORKSITE_CITY                        0.000
WORKSITE_STATE                       0.000
WORKSITE_POSTAL_CODE                 0.000
JOB_TITLE                            0.000
MINIMUM_EDUCATION                    0.000
MAJOR_FIELD_OF_STUDY                 0.000
REQUIRED_TRAINING                    0.000
REQUIRED_EXPERIENCE                  0.000
REQUIRED_EXPERIENCE_MONTHS           0.000
ACCEPT_ALT_FIELD_OF_STUDY            0.000
ACCEPT_ALT_COMBO                     0.000
ACCEPT_FOREIGN_EDUCATION             0.000
ACCEPT_ALT_OCCUPATION                0.000
ACCEPT_ALT_OCCUPATION_MONTHS         0.000
ACCEPT_ALT_JOB_TITLE                 0.000
JOB_OPP_REQUIREMENTS_NORMAL          0.000
FOREIGN_LANGUAGE_REQUIRED            0.000
SPECIFIC_SKILLS                      0.000
COMBINATION_OCCUPATION               0.000
OFFERED_TO_APPL_FOREIGN_WORKER       0.000
FOREIGN_WORKER_LIVE_ON_PREM          0.000
FOREIGN_WORKER_LIVE_IN_DOM_SER       0.000
PROFESSIONAL_OCCUPATION              0.000
APP_FOR_COLLEGE_U_TEACHER            0.000
SWA_JOB_ORDER_START_DATE             0.992
SWA_JOB_ORDER_END_DATE               0.992
SUNDAY_EDITION_NEWSPAPER             0.000
FIRST_NEWSPAPER_NAME                 0.000
FIRST_ADVERTISEMENT_START_DATE       0.992
SECOND_NEWSPAPER_AD_NAME             0.000
SECOND_ADVERTISEMENT_TYPE            0.000
SECOND_AD_START_DATE                 0.992
JOB_SEARCH_WEBSITE_FROM_DATE        22.596
JOB_SEARCH_WEBSITE_TO_DATE          22.596
LOCAL_ETHNIC_PAPER_FROM_DATE        39.104
LOCAL_ETHNIC_PAPER_TO_DATE          39.104
EMP_RECEIVED_PAYMENT                 0.000
POSTED_NOTICE_AT_WORKSITE            0.000
LAYOFF_IN_PAST_SIX_MONTHS            0.000
COUNTRY_OF_CITIZENSHIP               0.000
FOREIGN_WORKER_BIRTH_COUNTRY         0.000
CLASS_OF_ADMISSION                   0.000
FOREIGN_WORKER_EDUCATION             0.000
FOREIGN_WORKER_INFO_MAJOR            0.000
FOREIGN_WORKER_YRS_ED_COMP           0.000
FOREIGN_WORKER_INST_OF_ED            0.000
FOREIGN_WORKER_ED_INST_ADD_1         0.000
FOREIGN_WORKER_ED_INST_CITY          0.000
FOREIGN_WORKER_ED_INST_STATE_P       0.000
FOREIGN_WORKER_ED_INST_COUNTRY       0.000
FOREIGN_WORKER_ED_INST_POST_CD       0.000
FOREIGN_WORKER_REQ_EXPERIENCE        0.000
FOREIGN_WORKER_ALT_OCC_EXP           0.000
FOREIGN_WORKER_EXP_WITH_EMPL         0.000
FOREIGN_WORKER_EMPL_PAY_FOR_ED       0.000
FOREIGN_WORKER_CURR_EMPLOYED         0.000
EMPLOYER_COMPLETED_APPLICATION       0.000
PREPARER_NAME                        0.000
PREPARER_TITLE                       0.000
PREPARER_EMAIL                       0.000
EMP_INFO_DECL_NAME                   0.000
EMP_DECL_TITLE                       0.000
dtype: float64

## Removing more unnecessary columns

In [303]:
# Columns to be removed
columns_to_remove = [
    'EMPLOYER_PHONE', 'EMPLOYER_PHONE_EXT', 'EMPLOYER_POSTAL_CODE',
    'EMP_CONTACT_PHONE', 'EMP_CONTACT_EMAIL', 'AGENT_ATTORNEY_NAME',
    'AGENT_ATTORNEY_FIRM_NAME', 'AGENT_ATTORNEY_PHONE', 'AGENT_ATTORNEY_PHONE_EXT',
    'AGENT_ATTORNEY_ADDRESS_1', 'AGENT_ATTORNEY_ADDRESS_2', 'AGENT_ATTORNEY_EMAIL',
    'SWA_JOB_ORDER_START_DATE', 'SWA_JOB_ORDER_END_DATE', 'SUNDAY_EDITION_NEWSPAPER',
    'FIRST_NEWSPAPER_NAME', 'FIRST_ADVERTISEMENT_START_DATE', 'SECOND_NEWSPAPER_AD_NAME',
    'SECOND_ADVERTISEMENT_TYPE', 'SECOND_AD_START_DATE', 'JOB_SEARCH_WEBSITE_FROM_DATE',
    'JOB_SEARCH_WEBSITE_TO_DATE', 'LOCAL_ETHNIC_PAPER_FROM_DATE', 'LOCAL_ETHNIC_PAPER_TO_DATE',
    'EMP_CONTACT_ADDRESS_1', 'EMP_CONTACT_CITY', 'EMP_CONTACT_STATE_PROVINCE',
    'EMP_CONTACT_COUNTRY', 'EMP_CONTACT_POSTAL_CODE', 'PREPARER_NAME', 'PREPARER_TITLE',
    'PREPARER_EMAIL', 'EMP_INFO_DECL_NAME', 'EMP_DECL_TITLE'
]

# Remove specified columns
df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

# Confirm the remaining columns
print("Remaining columns:", df.columns)
print("Updated DataFrame shape:", df.shape)

Remaining columns: Index(['CASE_NUMBER', 'CASE_STATUS', 'RECEIVED_DATE', 'DECISION_DATE',
       'REFILE', 'SCHD_A_SHEEPHERDER', 'EMPLOYER_NAME', 'EMPLOYER_ADDRESS_1',
       'EMPLOYER_CITY', 'EMPLOYER_STATE_PROVINCE', 'EMPLOYER_COUNTRY',
       'EMPLOYER_NUM_EMPLOYEES', 'EMPLOYER_YEAR_COMMENCED_BUSINESS',
       'NAICS_CODE', 'FW_OWNERSHIP_INTEREST', 'EMP_CONTACT_NAME',
       'AGENT_ATTORNEY_CITY', 'AGENT_ATTORNEY_STATE_PROVINCE',
       'AGENT_ATTORNEY_COUNTRY', 'AGENT_ATTORNEY_POSTAL_CODE',
       'PW_TRACK_NUMBER', 'PW_SOC_CODE', 'PW_SOC_TITLE', 'PW_SKILL_LEVEL',
       'PW_WAGE', 'PW_UNIT_OF_PAY', 'PW_WAGE_SOURCE', 'PW_DETERMINATION_DATE',
       'PW_EXPIRATION_DATE', 'WAGE_OFFER_FROM', 'WAGE_OFFER_UNIT_OF_PAY',
       'WORKSITE_ADDRESS_1', 'WORKSITE_CITY', 'WORKSITE_STATE',
       'WORKSITE_POSTAL_CODE', 'JOB_TITLE', 'MINIMUM_EDUCATION',
       'MAJOR_FIELD_OF_STUDY', 'REQUIRED_TRAINING', 'REQUIRED_EXPERIENCE',
       'REQUIRED_EXPERIENCE_MONTHS', 'ACCEPT_ALT_FIELD_OF_STUDY',
       'ACCEPT_ALT_COMBO', 'ACCEPT_FOREIGN_EDUCATION', 'ACCEPT_ALT_OCCUPATION',
       'ACCEPT_ALT_OCCUPATION_MONTHS', 'ACCEPT_ALT_JOB_TITLE',
       'JOB_OPP_REQUIREMENTS_NORMAL', 'FOREIGN_LANGUAGE_REQUIRED',
       'SPECIFIC_SKILLS', 'COMBINATION_OCCUPATION',
       'OFFERED_TO_APPL_FOREIGN_WORKER', 'FOREIGN_WORKER_LIVE_ON_PREM',
       'FOREIGN_WORKER_LIVE_IN_DOM_SER', 'PROFESSIONAL_OCCUPATION',
       'APP_FOR_COLLEGE_U_TEACHER', 'EMP_RECEIVED_PAYMENT',
       'POSTED_NOTICE_AT_WORKSITE', 'LAYOFF_IN_PAST_SIX_MONTHS',
       'COUNTRY_OF_CITIZENSHIP', 'FOREIGN_WORKER_BIRTH_COUNTRY',
       'CLASS_OF_ADMISSION', 'FOREIGN_WORKER_EDUCATION',
       'FOREIGN_WORKER_INFO_MAJOR', 'FOREIGN_WORKER_YRS_ED_COMP',
       'FOREIGN_WORKER_INST_OF_ED', 'FOREIGN_WORKER_ED_INST_ADD_1',
       'FOREIGN_WORKER_ED_INST_CITY', 'FOREIGN_WORKER_ED_INST_STATE_P',
       'FOREIGN_WORKER_ED_INST_COUNTRY', 'FOREIGN_WORKER_ED_INST_POST_CD',
       'FOREIGN_WORKER_REQ_EXPERIENCE', 'FOREIGN_WORKER_ALT_OCC_EXP',
       'FOREIGN_WORKER_EXP_WITH_EMPL', 'FOREIGN_WORKER_EMPL_PAY_FOR_ED',
       'FOREIGN_WORKER_CURR_EMPLOYED', 'EMPLOYER_COMPLETED_APPLICATION'],
      dtype='object')
Updated DataFrame shape: (25000, 77)

In [304]:
df

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,REFILE,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,EMPLOYER_CITY,EMPLOYER_STATE_PROVINCE,EMPLOYER_COUNTRY,EMPLOYER_NUM_EMPLOYEES,EMPLOYER_YEAR_COMMENCED_BUSINESS,NAICS_CODE,FW_OWNERSHIP_INTEREST,EMP_CONTACT_NAME,AGENT_ATTORNEY_CITY,AGENT_ATTORNEY_STATE_PROVINCE,AGENT_ATTORNEY_COUNTRY,AGENT_ATTORNEY_POSTAL_CODE,PW_TRACK_NUMBER,PW_SOC_CODE,PW_SOC_TITLE,PW_SKILL_LEVEL,PW_WAGE,PW_UNIT_OF_PAY,PW_WAGE_SOURCE,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_UNIT_OF_PAY,WORKSITE_ADDRESS_1,WORKSITE_CITY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,JOB_TITLE,MINIMUM_EDUCATION,MAJOR_FIELD_OF_STUDY,REQUIRED_TRAINING,REQUIRED_EXPERIENCE,REQUIRED_EXPERIENCE_MONTHS,ACCEPT_ALT_FIELD_OF_STUDY,ACCEPT_ALT_COMBO,ACCEPT_FOREIGN_EDUCATION,ACCEPT_ALT_OCCUPATION,ACCEPT_ALT_OCCUPATION_MONTHS,ACCEPT_ALT_JOB_TITLE,JOB_OPP_REQUIREMENTS_NORMAL,FOREIGN_LANGUAGE_REQUIRED,SPECIFIC_SKILLS,COMBINATION_OCCUPATION,OFFERED_TO_APPL_FOREIGN_WORKER,FOREIGN_WORKER_LIVE_ON_PREM,FOREIGN_WORKER_LIVE_IN_DOM_SER,PROFESSIONAL_OCCUPATION,APP_FOR_COLLEGE_U_TEACHER,EMP_RECEIVED_PAYMENT,POSTED_NOTICE_AT_WORKSITE,LAYOFF_IN_PAST_SIX_MONTHS,COUNTRY_OF_CITIZENSHIP,FOREIGN_WORKER_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_EDUCATION,FOREIGN_WORKER_INFO_MAJOR,FOREIGN_WORKER_YRS_ED_COMP,FOREIGN_WORKER_INST_OF_ED,FOREIGN_WORKER_ED_INST_ADD_1,FOREIGN_WORKER_ED_INST_CITY,FOREIGN_WORKER_ED_INST_STATE_P,FOREIGN_WORKER_ED_INST_COUNTRY,FOREIGN_WORKER_ED_INST_POST_CD,FOREIGN_WORKER_REQ_EXPERIENCE,FOREIGN_WORKER_ALT_OCC_EXP,FOREIGN_WORKER_EXP_WITH_EMPL,FOREIGN_WORKER_EMPL_PAY_FOR_ED,FOREIGN_WORKER_CURR_EMPLOYED,EMPLOYER_COMPLETED_APPLICATION
0,A-22262-24149,Withdrawn,2022-10-02,2022-10-02,N,N,Westgate Shellworld Inc,7012 Muncipal Drive,Orlando,FLORIDA,UNITED STATES OF AMERICA,45,1988.0,453220,N,Samia Ahmed,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33172,P10021356781640,41-2031.00,RETAIL SALESPERSONS,Level I,20758.0,Year,OES,2022-06-21,2022-09-20,22880.0,Year,5870 US HWY 192,KISSIMMEE,FLORIDA,34746,SALES CLERK,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,N,Y,N,NICARAGUA,NICARAGUA,H-1B,High School,HIGH SCHOOL DIPLOMA,2010.0,INSTITUTO PUBLICO DE YALAGUINA,"DEL POLIDEPORTIVO MUNICIPAL, 400 MTRS. AL SURO...",SOMOTO,MADRIZ,NICARAGUA,600025,N,Y,N,N,N,N
1,A-21187-12839,Certified-Expired,2022-02-03,2022-10-03,N,N,"NIKE, INC.",ONE BOWERMAN DRIVE,BEAVERTON,OREGON,UNITED STATES OF AMERICA,35000,1969.0,316210,N,Diana L Loveless,Richardson,TEXAS,UNITED STATES OF AMERICA,75082,P10021127296744,11-2021,Marketing Managers,Level IV,167378.0,Year,OES,2021-10-21,2022-06-30,167378.0,Year,One Bowerman Dr.,Beaverton,OREGON,97005,Digital Services and Experiences Manager- Asia...,Master's,See H.14,N,Y,36.0,N,N,Y,Y,36.0,See H.14,N,N,Employer will accept Masters degree in Busines...,N,Y,N,N,Y,N,N,Y,N,THAILAND,THAILAND,L-1,Master's,BUSINESS ADMINISTRATION,2008.0,SIAM UNIVERSITY,"38 PETCHKASEM RD, BANG WA, KHET PHASI CHAROEN",BANGKOK,CA,THAILAND,10160,N,Y,N,N,Y,N
2,A-21327-77110,Denied,2021-11-30,2022-10-03,N,N,RIVERY TECHNOLOGIES INC,500 7TH AVENUE,NEW YORK,NEW YORK,UNITED STATES OF AMERICA,26,2019.0,54199,N,Michal Tshukati,New York,NEW YORK,UNITED STATES OF AMERICA,10006,P10021025032043,11-2021,Chief Executive Officer,Level IV,224307.0,Year,OES,2021-06-07,2021-09-05,224307.0,Year,500 7th Avenue,New York,NEW YORK,10018,Chief Executive Officer,Bachelor's,"Information Systems, Computer Engineering, or ...",N,N,24.0,N,N,Y,Y,120.0,Chief Executive Officer of a business intellig...,Y,N,Must have a Bachelors Degree in Information Sy...,N,Y,N,N,Y,N,N,Y,N,ISRAEL,ISRAEL,E-2,Bachelor's,INFORMATION SYSTEMS ENGINEERING,2002.0,BEN GURION UNIVERSITY OF THE NEGEV,1 BEN GURION AVENUE,BEER SHEVA,NEGEV,ISRAEL,8499000,N,Y,N,N,Y,N
3,A-21342-83195,Certified-Expired,2022-02-03,2022-10-03,N,N,ESRI INC.,380 NEW YORK ST.,REDLANDS,CALIFORNIA,UNITED STATES OF AMERICA,4000,1969.0,511210,N,Vinesh Patel,Washington,DISTRICT OF COLUMBIA,UNITED STATES OF AMERICA,20006,P10021137319941,11-2021,Marketing Managers,Level III,135990.0,Year,OES,2021-10-28,2022-06-30,135990.0,Year,55 Miracle Mile,Coral Gables,FLORIDA,33134,Business Development Manager,Master's,Business Administration,N,Y,36.0,Y,N,Y,Y,36.0,job offered or related occupation,Y,N,Applicants must have demonstrated experience w...,N,Y,N,N,Y,N,N,Y,N,CANADA,COLOMBIA,H-1B,Master's,CIVIL ENGINEERING,2014.0,RYERSON UNIVERSITY,350 VICTORIA ST,TORONTO,ONTARIO,CANADA,M5B 2K3,N,Y,N,N,Y,N
4,A-21349-86725,Certified-Expired,2022-02-03,2022-10-03,N,N,INGURAN LLC DBA STGENETICS,22575 STATE HWY 6 SOUTH,NAVASOTA,TEXAS,UNITED STATES OF AMERICA,666,2002.0,115210,N,Hayley R Harris,Houston,TEXAS,UNITED STATES OF AMERICA,77027,P10021040066303,11-2021,Marketing Managers,Level IV,179754.0,Year,OES,2021-06-30,2021-09-28,179754.0,Year,22575 State Highway 6 South,Navasota,TEXAS,77868,"Business Development Manager Asia, Oceania, Mi...",Master's,Business Administration,N,Y,60.0,Y,N,Y,N,24.0,See H.14,Y,N,60 MONTHS OF EMPLOYMENT EXPERIENCE AS A MARKET...,N,Y,N,N,Y,N,N,Y,N,UNITED KINGDOM,INDIA,Not in USA,Master's,BUSINESS ADMINISTRATION,2005.0,UNIVERSITY OF BIRMINGHAM,EDGBASTON,BIRMINGHAM,CA,UNITED KINGDOM,B15 2TT,Y,Y,N,N,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,A-21175-06798,Denied,2021-06-30,2022-12-28,N,N,"Stoughton Trailers, LLC",416 S. Academy St.,Stoughton,WISCONSIN,UNITED STATES OF AMERICA,1100,1961.0,336212,N,Todd Roller,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33130,P10020127547759,51-2092,TEAM ASSEMBLERS,Level I,29411.0,Year,OES,2020-08-21,2021-06-30,29411.0,Year,1111 VETERANS DRIVE,STOUGHTON,WISCONSIN,53589,ASSEMBLER,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,N,Y,N,COLOMBIA,COLOMBIA,H-1B,High School,HIGH SCHOOL DIPLOMA,1994.0,COLEGIO COOPERATIVO DEL MAGISTERIO DE CUNDINAM...,CALLE 16 BIS SUR NO. 12 C02,BOGOTA,CUNDINAMARCA,COLOMBIA,111511,N,Y,N,N,N,N
24996,A-21181-10313,Denied,2021-06-30,2022-12-28,N,N,"Stoughton Trailers, LLC",416 S. Academy St.,Stoughton,WISCONSIN,UNITED STATES OF AMERICA,1100,1961.0,336212,N,Todd Roller,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33130,P10020127547759,51-2092,TEAM ASSEMBLERS,Level I,29411.0,Year,OES,2020-08-21,2021-06-30,29411.0,Year,1111 VETERANS DRIVE,STOUGHTON,WISCONSIN,53589,ASSEMBLER,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,N,Y,N,BANGLADESH,BANGLADESH,H-1B,High School,HIGH SCHOOL DIPLOMA,2003.0,HABASPUR K. RAJ HIGH SCHOOL,"VILLPOSTHABASPUR, P.SPANGSHA, DISTRAJBARI",DHAKA,CA,BANGLADESH,600025,N,Y,N,N,N,N
24997,A-21181-10361,Denied,2021-06-30,2022-12-28,N,N,"Stoughton Trailers, LLC",416 S. Academy St.,Stoughton,WISCONSIN,UNITED STATES OF AMERICA,1100,1961.0,336212,N,Todd Roller,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33130,P10020127547759,51-2092,TEAM ASSEMBLERS,Level I,29411.0,Year,OES,2020-08-21,2021-06-30,29411.0,Year,1111 VETERANS DRIVE,STOUGHTON,WISCONSIN,53589,ASSEMBLER,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,N,Y,N,BANGLADESH,BANGLADESH,H-1B,High School,HIGH SCHOOL DIPLOMA,1992.0,CAPTAIN SHAMSUL HUDA HIGH SCHOOL,"MURADPUR, PO SITAKUNDA, CHITTAGONG",CHITTAGONG,CA,BANGLADESH,600025,N,Y,N,N,N,N
24998,A-22109-43004,Certified-Expired,2022-04-24,2022-12-28,N,N,"Stoughton Trailers, LLC",416 S. Academy St.,Stoughton,WISCONSIN,UNITED STATES OF AMERICA,1350,1961.0,336212,N,Todd Roller,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33172,P10021061113274,51-2092,TEAM ASSEMBLERS,Level I,29973.0,Year,OES,2021-07-26,2022-06-30,37440.0,Year,1111 VETERANS DRIVE,STOUGHTON,WISCONSIN,53589,ASSEMBLER,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,N,Y,N,BANGLADESH,BANGLADESH,H-1B,High School,HIGH SCHOOL DIPLOMA,2013.0,CHANDPUR GOVT.SECONDARY SCHOOL,TAZUMADDIN BAZAR,BHOLA,CA,BANGLADESH,600025,N,Y,N,N,N,N
24999,A-22109-43043,Certified-Expired,2022-04-22,2022-12-28,N,N,"Stoughton Trailers, LLC",416 S. Academy St.,Stoughton,WISCONSIN,UNITED STATES OF AMERICA,1350,1961.0,336212,N,Todd Roller,MIAMI,FLORIDA,UNITED STATES OF AMERICA,33172,P10021061113274,51-2092,TEAM ASSEMBLERS,Level I,29973.0,Year,OES,2021-07-26,2022-06-30,37440.0,Year,1111 VETERANS DRIVE,STOUGHTON,WISCONSIN,53589,ASSEMBLER,Master's,Computer Science,N,N,24.0,N,N,N,N,24.0,See H.14,Y,N,NONE,N,Y,N,N,N,N,N,Y,N,COLOMBIA,COLOMBIA,H-1B,High School,HIGH SCHOOL DIPLOMA,2008.0,GIMNASIO SANTA CRUZ,CRA 82 A #8099,BOGOTA,CA,COLOMBIA,600025,N,Y,N,N,N,N

In [305]:
# dtypes of df
df.dtypes

CASE_NUMBER                                 object
CASE_STATUS                               category
RECEIVED_DATE                       datetime64[ns]
DECISION_DATE                       datetime64[ns]
REFILE                                    category
SCHD_A_SHEEPHERDER                        category
EMPLOYER_NAME                               object
EMPLOYER_ADDRESS_1                          object
EMPLOYER_CITY                               object
EMPLOYER_STATE_PROVINCE                     object
EMPLOYER_COUNTRY                            object
EMPLOYER_NUM_EMPLOYEES                       int64
EMPLOYER_YEAR_COMMENCED_BUSINESS           float64
NAICS_CODE                                  object
FW_OWNERSHIP_INTEREST                       object
EMP_CONTACT_NAME                            object
AGENT_ATTORNEY_CITY                         object
AGENT_ATTORNEY_STATE_PROVINCE               object
AGENT_ATTORNEY_COUNTRY                      object
AGENT_ATTORNEY_POSTAL_CODE                  object
PW_TRACK_NUMBER                             object
PW_SOC_CODE                                 object
PW_SOC_TITLE                                object
PW_SKILL_LEVEL                              object
PW_WAGE                                    float64
PW_UNIT_OF_PAY                              object
PW_WAGE_SOURCE                              object
PW_DETERMINATION_DATE               datetime64[ns]
PW_EXPIRATION_DATE                  datetime64[ns]
WAGE_OFFER_FROM                            float64
WAGE_OFFER_UNIT_OF_PAY                      object
WORKSITE_ADDRESS_1                          object
WORKSITE_CITY                               object
WORKSITE_STATE                              object
WORKSITE_POSTAL_CODE                        object
JOB_TITLE                                   object
MINIMUM_EDUCATION                           object
MAJOR_FIELD_OF_STUDY                        object
REQUIRED_TRAINING                           object
REQUIRED_EXPERIENCE                         object
REQUIRED_EXPERIENCE_MONTHS                 float64
ACCEPT_ALT_FIELD_OF_STUDY                   object
ACCEPT_ALT_COMBO                            object
ACCEPT_FOREIGN_EDUCATION                    object
ACCEPT_ALT_OCCUPATION                       object
ACCEPT_ALT_OCCUPATION_MONTHS               float64
ACCEPT_ALT_JOB_TITLE                        object
JOB_OPP_REQUIREMENTS_NORMAL                 object
FOREIGN_LANGUAGE_REQUIRED                   object
SPECIFIC_SKILLS                             object
COMBINATION_OCCUPATION                      object
OFFERED_TO_APPL_FOREIGN_WORKER              object
FOREIGN_WORKER_LIVE_ON_PREM                 object
FOREIGN_WORKER_LIVE_IN_DOM_SER              object
PROFESSIONAL_OCCUPATION                     object
APP_FOR_COLLEGE_U_TEACHER                   object
EMP_RECEIVED_PAYMENT                        object
POSTED_NOTICE_AT_WORKSITE                   object
LAYOFF_IN_PAST_SIX_MONTHS                   object
COUNTRY_OF_CITIZENSHIP                      object
FOREIGN_WORKER_BIRTH_COUNTRY                object
CLASS_OF_ADMISSION                          object
FOREIGN_WORKER_EDUCATION                    object
FOREIGN_WORKER_INFO_MAJOR                   object
FOREIGN_WORKER_YRS_ED_COMP                 float64
FOREIGN_WORKER_INST_OF_ED                   object
FOREIGN_WORKER_ED_INST_ADD_1                object
FOREIGN_WORKER_ED_INST_CITY                 object
FOREIGN_WORKER_ED_INST_STATE_P              object
FOREIGN_WORKER_ED_INST_COUNTRY              object
FOREIGN_WORKER_ED_INST_POST_CD              object
FOREIGN_WORKER_REQ_EXPERIENCE               object
FOREIGN_WORKER_ALT_OCC_EXP                  object
FOREIGN_WORKER_EXP_WITH_EMPL                object
FOREIGN_WORKER_EMPL_PAY_FOR_ED              object
FOREIGN_WORKER_CURR_EMPLOYED                object
EMPLOYER_COMPLETED_APPLICATION              object
dtype: object

In [306]:
# Save the cleaned data to a new Excel file
output_path = 'D:/UCO_CourseWork/Programing for analytics/ProjectProposal/cleaned_data/Cleaned_PERM_Data_from_25kperm.xlsx'
df.to_excel(output_path, index=False)

# Provide the file path for download
output_path

'D:/UCO_CourseWork/Programing for analytics/ProjectProposal/cleaned_data/Cleaned_PERM_Data_from_25kperm.xlsx'

## Using the New Cleaned Dataset

In [ ]:
df = pd.read_excel(output_path)
df.shape

# Analysis Starts

In [ ]:
# Convert 'RECEIVED_DATE' and 'DECISION_DATE' to datetime format
df['RECEIVED_DATE'] = pd.to_datetime(df['RECEIVED_DATE'])
df['DECISION_DATE'] = pd.to_datetime(df['DECISION_DATE'])

# Extract year from 'RECEIVED_DATE' for analyses over the years
df['YEAR_RECEIVED'] = df['RECEIVED_DATE'].dt.year

## Question 1: What is the overall distribution of case statuses?

In [ ]:
# Calculate the distribution of case statuses
case_status_distribution = df['CASE_STATUS'].value_counts(normalize=True) * 100
print("Distribution of Case Statuses:")
print(case_status_distribution)

## Question 2: How many cases are filed each month?

In [ ]:
# Extract the month from the RECEIVED_DATE and count occurrences
df['RECEIVED_MONTH'] = df['RECEIVED_DATE'].dt.to_period('M')
monthly_cases = df['RECEIVED_MONTH'].value_counts().sort_index()
print("Number of Cases Filed Each Month:")
print(monthly_cases)

## Question 3: What are the top five employers employing foreign workers?

In [ ]:
# Count the top five employers in the dataset
top_employers = df['EMPLOYER_NAME'].value_counts().head(5)
print("Top Five Employers Employing Foreign Workers:")
print(top_employers)

## Question 4: What is the average processing time for all cases?

In [ ]:
# Calculate processing time by subtracting the received date from the decision date
df['PROCESSING_TIME'] = (df['DECISION_DATE'] - df['RECEIVED_DATE']).dt.days
average_processing_time = df['PROCESSING_TIME'].mean()
print("Average Processing Time for All Cases (in days):")
print(average_processing_time)

## Question 5: Which employer has filed the most cases?

In [ ]:
# Count the number of cases filed by each employer
top_employer = df['EMPLOYER_NAME'].value_counts().idxmax()
cases_count = df['EMPLOYER_NAME'].value_counts().max()
print("Employer with the Most Cases:")
print(f"{top_employer} with {cases_count} cases")

## Question 6: What are the trends in case outcomes over recent years?

In [ ]:
# Extract the year from the DECISION_DATE and calculate the outcome trends per year
df['DECISION_YEAR'] = df['DECISION_DATE'].dt.year
yearly_outcomes = df.pivot_table(index='DECISION_YEAR', columns='CASE_STATUS', aggfunc='size', fill_value=0)
print("Trends in Case Outcomes Over Recent Years:")
print(yearly_outcomes)

## Question 7: Which state has the highest number of cases filed?

In [ ]:

df['EMPLOYER_STATE'] = df['EMPLOYER_ADDRESS_1'].str.extract(r',\s*([^,]+)\s+\d+$')  # Regex to extract state
top_state = df['EMPLOYER_STATE'].value_counts().idxmax()
state_count = df['EMPLOYER_STATE'].value_counts().max()
print("State with the Highest Number of Cases Filed:")
print(f"{top_state} with {state_count} cases")

## Question 9: How do case results vary between industries?

In [ ]:
# Calculate case results by employer which serves as a proxy for industry
employer_outcomes = df.pivot_table(index='EMPLOYER_NAME', columns='CASE_STATUS', aggfunc='size', fill_value=0)
print("Case Results by Employer (as a proxy for Industry):")
employer_outcomes.head()  # Displaying the head to avoid too large output

## Question 11: What are the common job titles for which foreign workers are hired?

In [ ]:
# Calculate the frequency of job titles
common_job_titles = df['JOB_TITLE'].value_counts().head(10)
print("Common Job Titles for Which Foreign Workers are Hired:")
print(common_job_titles)

## Question 14: Are there seasonal trends in case filings or outcomes?

In [ ]:
# Extract month from RECEIVED_DATE and analyze filings by month
df['MONTH_RECEIVED'] = df['RECEIVED_DATE'].dt.month
seasonal_trends = df['MONTH_RECEIVED'].value_counts().sort_index()
print("Seasonal Trends in Case Filings:")
print(seasonal_trends)

## Question 15: What is the geographic distribution of foreign workers' intended workplaces?

In [ ]:
# Count cases by worksite state
geographic_distribution = df['WORKSITE_STATE'].value_counts()
print("Geographic Distribution of Foreign Workers' Intended Workplaces:")
print(geographic_distribution)

## Question 18: How often is foreign worker experience with the employing company mentioned?

In [ ]:
# Calculate frequency of mentions of foreign worker experience with employer
experience_with_employer = df['FOREIGN_WORKER_EXP_WITH_EMPL'].value_counts()
print("Frequency of Foreign Worker Experience with Employing Company Mentioned:")
print(experience_with_employer)

## Question 19: What are the trends in the educational requirements for the positions?

In [ ]:
# Analyze the trends in educational requirements using the 'MINIMUM_EDUCATION' column
education_trends = df['MINIMUM_EDUCATION'].value_counts()
print("Trends in Educational Requirements for Positions:")
print(education_trends)

## Question 20: How do the salaries offered compare to national averages for similar roles?

In [ ]:
# Calculate the average offered salary using the 'WAGE_OFFER_FROM' column
average_salary = df['WAGE_OFFER_FROM'].mean()

# Assuming a national average salary for similar roles
national_average = 50000 

print("Comparison of Offered Salaries to National Averages:")
print(f"Average Offered Salary: ${average_salary:.2f}")
print(f"National Average for Similar Roles: ${national_average}")

-------------

# Visualizations

## Question 1: How has the demand for foreign workers changed over the last three years across different sectors?

In [ ]:
# Convert 'RECEIVED_DATE' and 'DECISION_DATE' to datetime format
df['RECEIVED_DATE'] = pd.to_datetime(df['RECEIVED_DATE'])
df['DECISION_DATE'] = pd.to_datetime(df['DECISION_DATE'])

# Extract year from 'RECEIVED_DATE' for analyses over the years
df['YEAR_RECEIVED'] = df['RECEIVED_DATE'].dt.year

In [ ]:
# Filter df for the last three years
recent_data = df[df['YEAR_RECEIVED'] >= df['YEAR_RECEIVED'].max() - 2]


# Identify top employers in terms of number of applications filed
top_employers = recent_data['EMPLOYER_NAME'].value_counts().nlargest(10).index

# Filter data to include only the top employers
top_employer_data = recent_data[recent_data['EMPLOYER_NAME'].isin(top_employers)]

# Group by year and employer to count the number of applications
employer_demand_over_time = top_employer_data.groupby(['YEAR_RECEIVED', 'EMPLOYER_NAME']).size().unstack(fill_value=0)

# Plot the data
plt.figure(figsize=(14, 8))
sns.lineplot(data=employer_demand_over_time, markers=True, dashes=False)
plt.title('Demand for Foreign Workers Over the Last Five Years by Top Employers')
plt.ylabel('Number of Applications')
plt.xlabel('Year')
plt.xticks(sorted(recent_data['YEAR_RECEIVED'].unique()))  # Ensure all years are shown
plt.legend(title='Employer', title_fontsize='13', fontsize='11', loc='upper left')
plt.grid(True)
plt.show()

## Top Cities For Foreign Worker Employement by Employer Category

In [ ]:
# Classify 'EMPLOYER_NAME' into categories based on application volume
employer_counts = df['EMPLOYER_NAME'].value_counts()
df['EMPLOYER_CATEGORY'] = df['EMPLOYER_NAME'].apply(lambda x: 'High' if employer_counts[x] > 100 else ('Medium' if employer_counts[x] > 50 else 'Low'))

# Group data by employer category and city, and count the number of applications
city_employment = df.groupby(['EMPLOYER_CITY', 'EMPLOYER_CATEGORY']).size().reset_index(name='COUNT')

# Pivot the data
pivot_table = city_employment.pivot(index='EMPLOYER_CITY', columns='EMPLOYER_CATEGORY', values='COUNT')
pivot_table = pivot_table.fillna(0)  # Fill NaN with 0

# Make sure that the 'High' column exists even if it's all zeros
pivot_table['High'] = pivot_table.get('High', pd.Series([0]*pivot_table.shape[0]))

# Sorting the cities by 'High' volume category for better insight into top cities
pivot_table_sorted = pivot_table.sort_values(by='High', ascending=False)

# Visualizing the top cities for each employer category
plt.figure(figsize=(12, 10))
sns.heatmap(pivot_table_sorted.head(20), annot=True, fmt=".0f", cmap='viridis')
plt.title('Top Cities for Foreign Worker Employment by Employer Category')
plt.ylabel('City')
plt.xlabel('Employer Application Volume Category')
plt.show()

## 1. Bar Chart: Distribution of Case Statuses

In [ ]:
# Plotting the distribution of case statuses
plt.figure(figsize=(10, 6))
sns.countplot(x='CASE_STATUS', data=df)
plt.title('Distribution of Case Statuses')
plt.xlabel('Case Status')
plt.ylabel('Count')
plt.show()

## 2. Histogram: Distribution of Number of Employees Across Employers

In [ ]:
# Histogram of the number of employees
plt.figure(figsize=(10, 6))
sns.histplot(df['EMPLOYER_NUM_EMPLOYEES'], bins=30, kde=False)
plt.title('Distribution of Number of Employees Across Employers')
plt.xlabel('Number of Employees')
plt.ylabel('Frequency')
plt.show()

## 3. Line Plot: Trends Over Time in the Number of Applications Received Each Month

In [ ]:
# Create a monthly trend
monthly_trends = df.resample('M', on='RECEIVED_DATE').size()

plt.figure(figsize=(12, 6))
monthly_trends.plot(kind='line')
plt.title('Monthly Trends in Applications Received')
plt.xlabel('Month')
plt.ylabel('Number of Applications')
plt.show()

## 4. Box Plot: Distribution of Offered Wages Across Different Job Titles

In [ ]:
# Filtering to top 10 most common job titles for clarity in visualization
top_job_titles = df['JOB_TITLE'].value_counts().nlargest(10).index
filtered_df = df[df['JOB_TITLE'].isin(top_job_titles)]

plt.figure(figsize=(12, 8))
sns.boxplot(x='JOB_TITLE', y='WAGE_OFFER_FROM', data=filtered_df)
plt.title('Distribution of Offered Wages Across Different Job Titles')
plt.xlabel('Job Title')
plt.ylabel('Offered Wage')
plt.xticks(rotation=45)
plt.show()

## 5. Heatmap: Correlation Between Numeric Features

In [ ]:
# Selecting numeric features
numeric_features = df[['EMPLOYER_NUM_EMPLOYEES', 'PW_WAGE', 'WAGE_OFFER_FROM']]

# Calculating correlation matrix
correlation_matrix = numeric_features.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Between Numeric Features')
plt.show()

## 6. Violin Plot: Distributions of Offered Wages Using Employer States

In [ ]:
# Filtering to top 10 most common states for clarity in visualization
top_states = df['WORKSITE_STATE'].value_counts().nlargest(10).index
filtered_df = df[df['WORKSITE_STATE'].isin(top_states)]

plt.figure(figsize=(12, 8))
sns.violinplot(x='WORKSITE_STATE', y='WAGE_OFFER_FROM', data=filtered_df)
plt.title('Distribution of Offered Wages Across Different States')
plt.xlabel('State')
plt.ylabel('Offered Wage')
plt.xticks(rotation=45)
plt.show()

## 7. Violin Plot: Distributions of Offered Wages Using job skill level:

In [ ]:
# 'PW_SKILL_LEVEL' contains the job skill levels
top_skill_levels = df['PW_SKILL_LEVEL'].value_counts().nlargest(10).index
filtered_df = df[df['PW_SKILL_LEVEL'].isin(top_skill_levels)]

plt.figure(figsize=(12, 8))
sns.violinplot(x='PW_SKILL_LEVEL', y='WAGE_OFFER_FROM', data=filtered_df)
plt.title('Distribution of Offered Wages Across Different Skill Levels')
plt.xlabel('Skill Level')
plt.ylabel('Offered Wage')
plt.xticks(rotation=45)
plt.show()

## 7. Count Plot: Number of Applications by State and Case Status

In [ ]:
# Determine the top 15 states with the most applications
top_states = df['WORKSITE_STATE'].value_counts().nlargest(15).index

# Filter the dataframe to include only the top 15 states
filtered_df = df[df['WORKSITE_STATE'].isin(top_states)]

plt.figure(figsize=(14, 8))
sns.countplot(x='WORKSITE_STATE', hue='CASE_STATUS', data=filtered_df, order=top_states)
plt.title('Number of Applications by State and Case Status for Top 15 state')
plt.xlabel('Worksite State')
plt.ylabel('Number of Applications')
plt.xticks(rotation=45)
plt.legend(title='Case Status')
plt.show()

## 8. Scatter Plot: Relationship Between Employer Number of Employees and Prevailing Wage

In [ ]:
plt.figure(figsize=(10, 6))
sns.scatterplot(x='EMPLOYER_NUM_EMPLOYEES', y='PW_WAGE', data=df)
plt.title('Relationship Between Employer Number of Employees and Prevailing Wage')
plt.xlabel('Number of Employees')
plt.ylabel('Prevailing Wage')
plt.show()

## 9. Pair Plot: Visualizing Relationships and Distributions of Numeric Variables

In [ ]:
# Selecting a few numeric columns for the pair plot to keep the plot clear and readable
selected_columns = df[['EMPLOYER_NUM_EMPLOYEES', 'PW_WAGE', 'WAGE_OFFER_FROM']]
sns.pairplot(selected_columns)
plt.show()

## 14. Bar Chart: Frequency of Different Job Titles

In [ ]:
# Filtering to top 10 most common job titles
top_titles = df['JOB_TITLE'].value_counts().nlargest(10)
top_titles.plot(kind='bar', figsize=(12, 8))
plt.title('Frequency of Different Job Titles')
plt.xlabel('Job Title')
plt.ylabel('Frequency')
plt.xticks(rotation=45)
plt.show()

## 15. Count Plot: Distribution of Foreign Workers' Education Levels

In [ ]:
plt.figure(figsize=(10, 6))
sns.countplot(x='FOREIGN_WORKER_EDUCATION', data=df, order=df['FOREIGN_WORKER_EDUCATION'].value_counts().index)
plt.title('Distribution of Foreign Workers\' Education Levels')
plt.xlabel('Education Level')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

## 18. Bar Plot: Compare the Average Offered Wage in Different States

In [ ]:
# Group by state and calculate average offered wage
avg_wage_by_state = df.groupby('WORKSITE_STATE')['WAGE_OFFER_FROM'].mean().sort_values(ascending=False)

plt.figure(figsize=(14, 8))
avg_wage_by_state.plot(kind='bar')
plt.title('Average Offered Wage by State')
plt.xlabel('State')
plt.ylabel('Average Offered Wage')
plt.xticks(rotation=45)
plt.show()

## 21: Geographical Distribution of Cases Across the United States Using a Horizontal Bar Chart

In [ ]:

# Count of cases per state
state_counts = df['WORKSITE_STATE'].value_counts().reset_index()
state_counts.columns = ['state', 'count']

# Sorting the data to make the plot more readable
state_counts_sorted = state_counts.sort_values(by='count', ascending=True)

plt.figure(figsize=(10, 12))
sns.barplot(x='count', y='state', data=state_counts_sorted)
plt.title('Geographical Distribution of Cases Across the US')
plt.xlabel('Number of Cases')
plt.ylabel('State')
plt.show()

## 28. Pie Chart: Top Countries of Citizenship for Applicants

In [ ]:
# Determine the top 5 countries of citizenship
top_countries = df['COUNTRY_OF_CITIZENSHIP'].value_counts().nlargest(5)

# Choose a color palette for the pie chart
colors = plt.cm.Paired(range(len(top_countries)))

plt.figure(figsize=(10, 8))
plt.pie(top_countries, labels=top_countries.index, autopct='%1.1f%%', startangle=90, colors=colors, explode=(0.1, 0, 0, 0, 0))
plt.title('Top Countries of Citizenship of Applicants', pad=20)

# Move the legend to an appropriate place
plt.legend(title='Countries', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.show()